# Generated by Django 4.2.2 on 2023-06-19 20:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0005_alter_city_options_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Adres Başlık')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Ad')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('neighbourhood', models.CharField(max_length=100, null=True, verbose_name='Mahalle')),
                ('bill_type', models.CharField(choices=[('Bireysel', 'Bireysel'), ('Kurumsal', 'Kurumsal')], max_length=20, null=True, verbose_name='Fatura Tipi')),
                ('tc', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='T.C. Kimlik Numarası')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket Adı')),
                ('tax_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Vergi Numarası')),
                ('tax_administration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Geçerli Adres Yap')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.city', verbose_name='Şehir')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.county', verbose_name='İlçe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1) Müşteri Adresleri',
                'verbose_name_plural': '1) Müşteri Adresleri',
            },
        ),
    ]
