# Generated by Django 3.2.21 on 2024-03-02 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
        ('categorymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=300, null=True, verbose_name='Email Adresi')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Abonelikler',
                'verbose_name_plural': '2) Abonelikler',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Adres Başlık')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Soyad')),
                ('mobile', models.CharField(max_length=50, null=True, verbose_name='Telefon Numarası')),
                ('neighbourhood', models.CharField(max_length=100, null=True, verbose_name='Mahalle')),
                ('address', models.TextField(max_length=1000, null=True, verbose_name='Adres Detay')),
                ('bill_type', models.CharField(choices=[('Bireysel', 'Bireysel'), ('Kurumsal', 'Kurumsal')], max_length=20, null=True, verbose_name='Fatura Tipi')),
                ('tc', models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C. Kimlik Numarası')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket Adı')),
                ('tax_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vergi Numarası')),
                ('tax_administration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi')),
                ('is_active', models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Evet', max_length=20, null=True, verbose_name='Geçerli Adres Yap')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.city', verbose_name='Şehir')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.county', verbose_name='İlçe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '1) Müşteri Adresleri',
                'verbose_name_plural': '1) Müşteri Adresleri',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, null=True, verbose_name='Kupon Kodu')),
                ('coupon_price', models.FloatField(null=True, verbose_name='Kupon Fiyatı')),
                ('coupon_conditional', models.BigIntegerField(verbose_name='Kupon Şartı')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='Kullanımda mı?')),
                ('start_date', models.DateField(null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(null=True, verbose_name='Bitiş Tarihi')),
                ('is_completed', models.BooleanField(default=False, null=True, verbose_name='Süresi bitti mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('coupon_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.maincategory', verbose_name='İlgili Kategori')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '4) Müşteri Kuponları',
                'verbose_name_plural': '4) Müşteri Kuponları',
            },
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuses', models.FloatField(verbose_name='Bonus')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '3) Müşteri Bonusları',
                'verbose_name_plural': '3) Müşteri Bonusları',
            },
        ),
    ]
