# Generated by Django 3.2.21 on 2023-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='is_active',
            field=models.CharField(choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Evet', max_length=20, null=True, verbose_name='Geçerli Adres Yap'),
        ),
    ]
