# Generated by Django 4.2.2 on 2023-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address',
            field=models.TextField(max_length=1000, null=True, verbose_name='Adres Detay'),
        ),
    ]
