# Generated by Django 4.2.2 on 2023-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customeraddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='is_active',
            field=models.CharField(blank=True, choices=[('Evet', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=20, null=True, verbose_name='Geçerli Adres Yap'),
        ),
    ]
