# Generated by Django 4.2.2 on 2023-06-20 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customeraddress_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='T.C. Kimlik Numarası'),
        ),
    ]
