# Generated by Django 4.2.2 on 2023-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customeraddress_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='tax_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C. Kimlik Numarası'),
        ),
    ]
