# Generated by Django 4.2.2 on 2023-06-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customeraddress_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
