# Generated by Django 4.2.2 on 2023-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customeraddress_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Soyad'),
        ),
    ]
