# Generated by Django 4.2.2 on 2023-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
