# Generated by Django 4.2.2 on 2023-07-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0011_alter_maincategory_options_maincategory_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_subscription_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '2) Abonelikler', 'verbose_name_plural': '2) Abonelikler'},
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.FloatField(verbose_name='Kupon Kodu')),
                ('coupon_conditional', models.BigIntegerField(verbose_name='Kupon Şartı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('coupon_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.maincategory', verbose_name='İlgili Kategori')),
                ('user', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Müşteriler')),
            ],
            options={
                'verbose_name': '3) Müşteri Bonusları',
                'verbose_name_plural': '2) Müşteri Bonusları',
            },
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonuses', models.FloatField(verbose_name='Bonus')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '3) Müşteri Bonusları',
                'verbose_name_plural': '2) Müşteri Bonusları',
            },
        ),
    ]
