# Generated by Django 4.2.2 on 2023-07-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_subscription_options_coupon_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_price',
            field=models.FloatField(null=True, verbose_name='Kupon Fiyatı'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Kupon Kodu'),
        ),
    ]
