# Generated by Django 4.2.2 on 2023-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_coupon_coupon_price_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False, null=True, verbose_name='Kullanımda mı?'),
        ),
    ]
