# Generated by Django 4.2.2 on 2023-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_coupon_user_coupon_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuses',
            options={'verbose_name': '3) Müşteri Bonusları', 'verbose_name_plural': '3) Müşteri Bonusları'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '4) Müşteri Kuponları', 'verbose_name_plural': '4) Müşteri Kuponları'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Başlangıç Tarihi'),
        ),
    ]
