# Generated by Django 4.2.2 on 2023-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_bonuses_options_alter_coupon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_completed',
            field=models.BooleanField(default=False, null=True, verbose_name='Süresi bitti mi?'),
        ),
    ]
