# Generated by Django 4.2.2 on 2023-07-19 18:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorymodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Marka Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Markalar',
                'verbose_name_plural': '2) Markalar',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Renk')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Renk Kodu')),
            ],
            options={
                'verbose_name': 'Renkler',
                'verbose_name_plural': 'Renkler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='img/product/', verbose_name='Kapak Resmi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fiyat')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('is_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla')),
                ('amount', models.IntegerField(verbose_name='Miktar')),
                ('stock_code', models.CharField(max_length=50, null=True, verbose_name='Stok Kodu')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detay')),
                ('variant', models.CharField(blank=True, choices=[('Renk-Boyut', 'Renk-Boyut'), ('Renk', 'Renk'), ('Boyut', 'Boyut'), ('Yok', 'Yok')], default='Yok', max_length=20, null=True, verbose_name='Tip')),
                ('is_publish', models.BooleanField(default=True, null=True, verbose_name='Yayında mı?')),
                ('sell_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='categorymodel.maincategory', verbose_name='Ana Kategori')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='categorymodel.subcategory', verbose_name='Alt Kategori')),
            ],
            options={
                'verbose_name': '1) Ürünler',
                'verbose_name_plural': '1) Ürünler',
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=200)),
                ('rating', models.FloatField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3) Yorum ve Oylama Sistemi',
                'verbose_name_plural': '3) Yorum ve Oylama Sistemi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Boyut')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Boyut Kodu')),
            ],
            options={
                'verbose_name': 'Boyut/Kapasite',
                'verbose_name_plural': 'Boyut/Kapasite',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Miktar')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('is_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla')),
                ('is_publish', models.BooleanField(default=True, null=True, verbose_name='Yayında mı?')),
                ('sell_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Boyut')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=120, verbose_name='İp Adresi')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '8) Gelince Haber Ver',
                'verbose_name_plural': '8) Gelince Haber Ver',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Açıklama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Ürüne Ait Özellikler',
                'verbose_name_plural': 'Ürüne Ait Özellikler',
            },
        ),
        migrations.CreateModel(
            name='ReviewRatingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='img/product/comments/', verbose_name='Fotoğraf')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True, verbose_name='Soru')),
                ('answer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Cevap')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '7) Soru ve Cevaplar',
                'verbose_name_plural': '7) Soru ve Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='ProductKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True, verbose_name='Anahtar Kelime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Anahtar Kelime',
                'verbose_name_plural': 'Anahtar Kelime',
            },
        ),
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '4) Beğenilen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, upload_to='img/product/', verbose_name='Resim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Ürüne Ait Resimler',
                'verbose_name_plural': 'Ürüne Ait Resimler',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '6) Favorilere Eklenen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='DisLikeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '5) Beğenilmeyen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='DescriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=100, null=True, verbose_name='Açıklama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Öne Çıkan Açıklamalar',
                'verbose_name_plural': 'Öne Çıkan Açıklamalar',
            },
        ),
    ]
