# Generated by Django 3.2.21 on 2024-03-02 16:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorymodel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kol Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='BagPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Çanta Deseni')),
            ],
        ),
        migrations.CreateModel(
            name='BijuteriTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tema/Stil')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Marka Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Marka',
                'verbose_name_plural': '2) Markalar',
            },
        ),
        migrations.CreateModel(
            name='CollerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yaka Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Renk')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk Kodu')),
            ],
            options={
                'verbose_name': '9.1) Renk',
                'verbose_name_plural': '9.1) Renkler',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ortam')),
            ],
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kumaş Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='HeelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topuk Boyu')),
            ],
        ),
        migrations.CreateModel(
            name='HeelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topuk Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Boy')),
            ],
        ),
        migrations.CreateModel(
            name='KadinAltBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.IntegerField(null=True, verbose_name='EU-TR Beden')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Alt Beden Tablosu',
                'verbose_name_plural': 'Kadın Alt Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinAltBuyukBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.IntegerField(null=True, verbose_name='EU-TR Beden')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Alt Büyük Beden Tablosu',
                'verbose_name_plural': 'Kadın Alt Büyük Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinJeanBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.CharField(max_length=50, null=True, verbose_name='EU-TR Beden')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Jean Beden Tablosu',
                'verbose_name_plural': 'Kadın Jean Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinUstBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.IntegerField(null=True, verbose_name='EU-TR Beden')),
                ('boyun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyun (cm)')),
                ('gogus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Göğüs (cm)')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Üst Beden Tablosu',
                'verbose_name_plural': 'Kadın Üst Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinUstBuyukBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.IntegerField(null=True, verbose_name='EU-TR Beden')),
                ('boyun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyun (cm)')),
                ('gogus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Göğüs (cm)')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Üst Büyük Beden Tablosu',
                'verbose_name_plural': 'Kadın Üst Büyük Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='LegType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Paça Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Materyal')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kalıp')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cep')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='XML ID')),
                ('barcode', models.CharField(max_length=100, null=True, unique=True, verbose_name='Barkod')),
                ('model_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Kodu')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('dropshipping', models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.CharField(max_length=355, verbose_name='Açıklama')),
                ('image_url1', models.CharField(max_length=500, null=True, verbose_name='Resim Link 1')),
                ('image_url2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 2')),
                ('image_url3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 3')),
                ('image_url4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 4')),
                ('image_url5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 5')),
                ('image_url6', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 6')),
                ('image_url7', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 7')),
                ('image_url8', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 8')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fiyat')),
                ('quantity', models.BigIntegerField(default=0, null=True, verbose_name='Miktar')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('is_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla')),
                ('age_group', models.CharField(blank=True, choices=[('Bebek', 'Bebek'), ('Bebek&Çocuk', 'Bebek&Çocuk'), ('Çocuk', 'Çocuk'), ('Genç', 'Genç'), ('Yetişkin', 'Yetişkin')], max_length=50, null=True, verbose_name='Yaş Grubu')),
                ('is_publish', models.BooleanField(default=True, null=True, verbose_name='Yayında mı?')),
                ('sell_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('armtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.armtype', verbose_name='Kol Tipi')),
                ('bag_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bagpattern', verbose_name='Çanta Deseni')),
                ('bijuteri_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bijuteritheme', verbose_name='Tema/Stil')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_brands', to='product.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_main_category', to='categorymodel.maincategory', verbose_name='1. Düzey Kategori')),
                ('collartype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.collertype', verbose_name='Yaka Tipi')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.environmenttype', verbose_name='Ortam')),
                ('fabrictype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.fabrictype', verbose_name='Kumaş Tipi')),
                ('heelsize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.heelsize', verbose_name='Topuk Boyu')),
                ('heeltype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.heeltype', verbose_name='Topuk Tipi')),
                ('height', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.height', verbose_name='Boy')),
                ('legtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.legtype', verbose_name='Paça Tipi')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.materialtype', verbose_name='Materyal')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.pattern', verbose_name='Kalıp')),
                ('pocket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.pocket', verbose_name='Cep')),
            ],
            options={
                'verbose_name': '1) Ürünler',
                'verbose_name_plural': '1) Ürünler',
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=200)),
                ('rating', models.FloatField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3) Yorum ve Oylama Sistemi',
                'verbose_name_plural': '3) Yorum ve Oylama Sistemi',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cinsiyet')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Boyut')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyut Kodu')),
            ],
            options={
                'verbose_name': '9.2) Boyut/Kapasite',
                'verbose_name_plural': '9.2) Boyut/Kapasite',
            },
        ),
        migrations.CreateModel(
            name='SleepMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Uyku Modu')),
            ],
        ),
        migrations.CreateModel(
            name='TableCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kılıf Modeli')),
            ],
        ),
        migrations.CreateModel(
            name='TabletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tablet Modelleri')),
            ],
        ),
        migrations.CreateModel(
            name='Waist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bel')),
            ],
        ),
        migrations.CreateModel(
            name='WeavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dokuma Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=120, verbose_name='İp Adresi')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '8) Gelince Haber Ver',
                'verbose_name_plural': '8) Gelince Haber Ver',
            },
        ),
        migrations.CreateModel(
            name='ReviewRatingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='img/product/comments/', verbose_name='Fotoğraf')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True, verbose_name='Soru')),
                ('answer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Cevap')),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '7) Soru ve Cevaplar',
                'verbose_name_plural': '7) Soru ve Cevaplar',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.CharField(max_length=355, verbose_name='Açıklama')),
                ('model_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Kodu')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('is_publish', models.BooleanField(default=True, null=True, verbose_name='Yayında mı?')),
                ('is_publish_trendyol', models.BooleanField(default=False, null=True, verbose_name='Trendyolda Yayında Mı?')),
                ('is_publish_hepsiburada', models.BooleanField(default=False, null=True, verbose_name='Hepsiburadada Yayında Mı?')),
                ('is_publish_ciceksepeti', models.BooleanField(default=False, null=True, verbose_name='Çiçeksepetinde Yayında Mı?')),
                ('quantity', models.BigIntegerField(default=0, null=True, verbose_name='Miktar')),
                ('trendyol_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol Fiyatı')),
                ('trendyol_discountprice', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol İndirimli Fiyatı')),
                ('is_trendyol_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='Trendyol İndirim Durumu')),
                ('ciceksepeti_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Çiçeksepeti Fiyatı')),
                ('ciceksepeti_discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Çiçeksepeti İndirimli Fiyatı')),
                ('is_ciceksepeti_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='Çiçeksepeti İndirim Durumu')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Renk')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Boyut/Beden')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sextype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sex', verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='product',
            name='subbottomcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_subbottom_category', to='categorymodel.subbottomcategory', verbose_name='3. Düzey Kategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_sub_category', to='categorymodel.subcategory', verbose_name='2. Düzey Kategori'),
        ),
        migrations.AddField(
            model_name='product',
            name='waist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.waist', verbose_name='Bel'),
        ),
        migrations.AddField(
            model_name='product',
            name='weavingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.weavingtype', verbose_name='Dokuma Tipi'),
        ),
        migrations.CreateModel(
            name='LikeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '4) Beğenilen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '6) Favorilere Eklenen Ürünler',
            },
        ),
        migrations.CreateModel(
            name='DisLikeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_product', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike_product', to='product.product')),
            ],
            options={
                'verbose_name_plural': '5) Beğenilmeyen Ürünler',
            },
        ),
    ]
