# Generated by Django 3.2.21 on 2024-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_stock_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kdv',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KDV Oranı'),
        ),
    ]
