# Generated by Django 4.2.2 on 2023-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_images_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Ürüne Ait Resimler', 'verbose_name_plural': 'Ürüne Ait Resimler'},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/product/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Başlık'),
        ),
    ]
