# Generated by Django 3.2.21 on 2024-03-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_kdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Barkod'),
        ),
    ]
