# Generated by Django 4.2.2 on 2023-07-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_barcode_alter_product_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '2) Marka', 'verbose_name_plural': '2) Markalar'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': '9.1) Renk', 'verbose_name_plural': '9.1) Renkler'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '1) Ürün', 'verbose_name_plural': '1) Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': '9.2) Boyut/Kapasite', 'verbose_name_plural': '9.2) Boyut/Kapasite'},
        ),
    ]
