# Generated by Django 4.2.2 on 2023-07-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=500, null=True, verbose_name='Anahtar Kelime'),
        ),
    ]
