# Generated by Django 4.2.2 on 2023-06-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_images_options_alter_images_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(verbose_name='Detay'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/product/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keyword',
            field=models.CharField(max_length=255, verbose_name='Anahtar Kelime'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
    ]
