# Generated by Django 3.2.21 on 2024-03-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productvariant_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Varyant', 'verbose_name_plural': 'Varyant'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
