# Generated by Django 4.2.2 on 2023-07-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=500, null=True, verbose_name='Resim Link'),
        ),
    ]
