# Generated by Django 3.2.21 on 2024-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20240303_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_completed_category',
            field=models.BooleanField(default=False, null=True, verbose_name='Tüm Kategoriler Dolduruldu Mu?'),
        ),
    ]
