# Generated by Django 4.2.2 on 2023-07-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='xml_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='XML ID'),
        ),
    ]
