# Generated by Django 4.2.2 on 2023-06-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0010_alter_maincategory_options_alter_subcategory_options_and_more'),
        ('product', '0007_product_subcategory_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.maincategory', verbose_name='Ana Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.subcategory', verbose_name='Alt Kategori'),
        ),
    ]
