# Generated by Django 3.2.21 on 2024-03-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_completed_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Desen')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='desen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.desen', verbose_name='Desen'),
        ),
    ]
