# Generated by Django 4.2.2 on 2023-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_xml_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image_url',
            field=models.CharField(max_length=500, null=True, verbose_name='Resim Link'),
        ),
    ]
