# Generated by Django 3.2.21 on 2024-03-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240315_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumaTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dokuma Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='Koleksiyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Koleksiyon')),
            ],
        ),
        migrations.CreateModel(
            name='Ozellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Özellik')),
            ],
        ),
        migrations.CreateModel(
            name='PaketIcerigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Paket İçeriği')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dokuma_tipi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.dokumatipi', verbose_name='Dokuma Tipi'),
        ),
        migrations.AddField(
            model_name='product',
            name='koleksiyon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.koleksiyon', verbose_name='Koleksiyon'),
        ),
        migrations.AddField(
            model_name='product',
            name='ozellik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ozellik', verbose_name='Özellik'),
        ),
        migrations.AddField(
            model_name='product',
            name='paket_icerigi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.paketicerigi', verbose_name='Paket İçeriği'),
        ),
    ]
