# Generated by Django 4.2.2 on 2023-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Marka Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Markalar',
                'verbose_name_plural': '2) Markalar',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '1) Ürünler', 'verbose_name_plural': '1) Ürünler'},
        ),
    ]
