# Generated by Django 4.2.2 on 2023-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_images_image_images_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/product/', verbose_name='Resim'),
        ),
    ]
