# Generated by Django 3.2.21 on 2024-03-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20240315_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrunDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ürün Detay')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='urundetay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.urundetay', verbose_name='Ürün Detay'),
        ),
    ]
