# Generated by Django 4.2.2 on 2023-07-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_hepsiburada_price_product_pttavm_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='hepsiburada_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Hepsiburada Fiyatı'),
        ),
        migrations.AddField(
            model_name='variants',
            name='pttavm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='PttAvm Fiyatı'),
        ),
        migrations.AddField(
            model_name='variants',
            name='trendyol_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol Fiyatı'),
        ),
    ]
