# Generated by Django 4.2.2 on 2023-06-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0011_alter_maincategory_options_maincategory_order'),
        ('product', '0010_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='categorymodel.maincategory', verbose_name='Ana Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='categorymodel.subcategory', verbose_name='Alt Kategori'),
        ),
    ]
