# Generated by Django 3.2.21 on 2024-03-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20240316_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siluet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Silüet')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='siluet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.siluet', verbose_name='Silüet'),
        ),
    ]
