# Generated by Django 4.2.2 on 2023-07-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_variants_hepsiburada_price_variants_pttavm_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kombinasyon SKU'),
        ),
    ]
