# Generated by Django 4.2.2 on 2023-06-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Ürüne Ait Özellikler', 'verbose_name_plural': 'Ürüne Ait Özellikler'},
        ),
        migrations.AlterField(
            model_name='specification',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Açıklama'),
        ),
        migrations.CreateModel(
            name='DescriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Başlık')),
                ('list', models.CharField(max_length=100, null=True, verbose_name='Açıklama')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Öne Çıkan Açıklamalar',
                'verbose_name_plural': 'Öne Çıkan Açıklamalar',
            },
        ),
    ]
