# Generated by Django 3.2.21 on 2024-03-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20240316_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltSiluet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Alt Silüet')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='altsiluet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.altsiluet', verbose_name='Alt Silüet'),
        ),
    ]
