# Generated by Django 4.2.2 on 2023-07-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_variants_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='gtin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gtin'),
        ),
    ]
