# Generated by Django 4.2.2 on 2023-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_specification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionlist',
            name='title',
        ),
    ]
