# Generated by Django 4.2.2 on 2023-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_variants_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropshippin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform'),
        ),
    ]
