# Generated by Django 4.2.2 on 2023-07-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_dropshippin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dropshippin',
            new_name='dropshipping',
        ),
    ]
