# Generated by Django 4.2.2 on 2023-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_code',
            field=models.CharField(max_length=50, null=True, verbose_name='Stok Kodu'),
        ),
    ]
