# Generated by Django 4.2.2 on 2023-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publis_trendyol',
            field=models.BooleanField(default=False, null=True, verbose_name='Trendyolda Yayında Mı?'),
        ),
    ]
