# Generated by Django 4.2.2 on 2023-06-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_stock_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keyword',
        ),
        migrations.CreateModel(
            name='ProductKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, null=True, verbose_name='Anahtar Kelime')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Anahtar Kelime',
                'verbose_name_plural': 'Anahtar Kelime',
            },
        ),
    ]
