# Generated by Django 4.2.2 on 2023-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_keyword_productkeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discountprice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla'),
        ),
    ]
