# Generated by Django 4.2.2 on 2023-08-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_is_publis_trendyol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_publis_trendyol',
            new_name='is_publish_trendyol',
        ),
    ]
