# Generated by Django 4.2.2 on 2023-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_rename_is_publis_trendyol_product_is_publish_trendyol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Mevcut mu?'),
        ),
    ]
