# Generated by Django 4.2.2 on 2023-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk Kodu'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='dislikeproduct',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='likeproduct',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, choices=[('Renk-Boyut', 'Renk-Boyut'), ('Renk', 'Renk'), ('Boyut', 'Boyut'), ('Yok', 'Yok')], default='Yok', max_length=50, null=True, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyut Kodu'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Boyut'),
        ),
    ]
