# Generated by Django 4.2.2 on 2023-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_reviewrating_likeproduct_favorite_dislikeproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='subject',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='images',
            field=models.ImageField(blank=True, upload_to='img/product/comments/', verbose_name='Fotoğraf'),
        ),
    ]
