# Generated by Django 4.2.2 on 2023-06-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_reviewrating_subject_reviewrating_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='images',
        ),
        migrations.CreateModel(
            name='ReviewRatingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='img/product/comments/', verbose_name='Fotoğraf')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.reviewrating')),
            ],
        ),
    ]
