# Generated by Django 4.2.2 on 2023-09-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_color_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Başlık'),
        ),
    ]
