# Generated by Django 4.2.2 on 2023-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_product_keywords_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='gtin',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Gtin'),
        ),
    ]
