# Generated by Django 4.2.2 on 2023-06-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_reviewrating_images_reviewratingimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislikeproduct',
            options={'verbose_name_plural': '5) Beğenilmeyen Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': '6) Favorilere Eklenen Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='likeproduct',
            options={'verbose_name_plural': '4) Beğenilen Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': '3) Yorum ve Oylama Sistemi', 'verbose_name_plural': '3) Yorum ve Oylama Sistemi'},
        ),
        migrations.AddField(
            model_name='reviewratingimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
