# Generated by Django 4.2.2 on 2023-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_variants_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='gtin',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Gtin'),
        ),
    ]
