# Generated by Django 4.2.2 on 2023-06-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_reviewrating_options_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '7) Soru ve Cevaplar', 'verbose_name_plural': '7) Soru ve Cevaplar'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default='1', null=True, verbose_name='Miktar'),
        ),
    ]
