# Generated by Django 4.2.2 on 2023-06-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_question_options_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
