# Generated by Django 4.2.2 on 2023-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_variants_gtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Stok Kodu'),
        ),
    ]
