# Generated by Django 4.2.2 on 2023-06-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Renk')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Renk Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Boyut')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Boyut Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Miktar')),
                ('price', models.FloatField(default=0, verbose_name='Fiyat')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('is_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Boyut')),
            ],
        ),
    ]
