# Generated by Django 4.2.2 on 2023-09-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_product_trendyol_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trendyol_category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Trendyol Kategori Numarası'),
        ),
    ]
