# Generated by Django 4.2.2 on 2023-09-12 08:40

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0013_delete_trendyolfirstcategory_and_more'),
        ('product', '0027_alter_product_trendyol_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='XML ID')),
                ('barcode', models.CharField(max_length=100, null=True, unique=True, verbose_name='Barkod')),
                ('model_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Kodu')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('dropshipping', models.CharField(blank=True, max_length=255, null=True, verbose_name='Platform')),
                ('trendyol_category_id', models.BigIntegerField(blank=True, null=True, verbose_name='Trendyol Kategori Numarası')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('image_url1', models.CharField(max_length=500, null=True, verbose_name='Resim Link 1')),
                ('image_url2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 2')),
                ('image_url3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 3')),
                ('image_url4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 4')),
                ('image_url5', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 5')),
                ('image_url6', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 6')),
                ('image_url7', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 7')),
                ('image_url8', models.CharField(blank=True, max_length=500, null=True, verbose_name='Resim Link 8')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Fiyat')),
                ('detail', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Detay')),
                ('trendyol_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol Fiyatı')),
                ('hepsiburada_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Hepsiburada Fiyatı')),
                ('pttavm_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='PttAvm Fiyatı')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('is_discountprice', models.BooleanField(blank=True, default=False, null=True, verbose_name='İndirimli Yayınla')),
                ('age_group', models.CharField(choices=[('Bebek', 'Bebek'), ('Bebek&Çocuk', 'Bebek&Çocuk'), ('Çocuk', 'Çocuk'), ('Genç', 'Genç'), ('Yetişkin', 'Yetişkin')], max_length=50, verbose_name='Yaş Grubu')),
                ('sex', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın/Kız', 'Kadın/Kız'), ('Unisex', 'Unisex')], max_length=50, verbose_name='Cinsiyet')),
                ('is_publish', models.BooleanField(default=True, null=True, verbose_name='Yayında mı?')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Mevcut mu?')),
                ('is_publish_trendyol', models.BooleanField(default=False, null=True, verbose_name='Trendyolda Yayında Mı?')),
                ('sell_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_brands', to='product.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_main_category', to='categorymodel.maincategory', verbose_name='1. Düzey Kategori')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='Renk')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Boyut/Beden')),
                ('subbottomcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_subbottom_category', to='categorymodel.subbottomcategory', verbose_name='3. Düzey Kategori')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_sub_category', to='categorymodel.subcategory', verbose_name='2. Düzey Kategori')),
            ],
        ),
    ]
