# Generated by Django 4.2.2 on 2023-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_variants_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, choices=[('Renk-Boyut', 'Renk-Boyut'), ('Renk', 'Renk'), ('Boyut', 'Boyut')], max_length=20, null=True, verbose_name='Tip'),
        ),
    ]
