# Generated by Django 4.2.2 on 2023-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, choices=[('Renk-Boyut', 'Renk-Boyut'), ('Renk', 'Renk'), ('Boyut', 'Boyut'), ('Yok', 'Yok')], default='Yok', max_length=20, null=True, verbose_name='Tip'),
        ),
    ]
