# Generated by Django 4.2.2 on 2023-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_apiproduct_age_group_alter_apiproduct_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='quantity',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Miktar'),
        ),
    ]
