# Generated by Django 4.2.2 on 2023-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True, null=True, verbose_name='Yayında mı?'),
        ),
        migrations.AddField(
            model_name='variants',
            name='is_publish',
            field=models.BooleanField(default=True, null=True, verbose_name='Yayında mı?'),
        ),
    ]
