# Generated by Django 4.2.2 on 2023-09-20 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_apiproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
