# Generated by Django 4.2.2 on 2023-07-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_stockalarm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Renkler', 'verbose_name_plural': 'Renkler'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Boyut/Kapasite', 'verbose_name_plural': 'Boyut/Kapasite'},
        ),
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı'),
        ),
        migrations.AddField(
            model_name='variants',
            name='sell_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı'),
        ),
    ]
