# Generated by Django 4.2.2 on 2023-09-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_fabrictype_height_pattern_apiproduct_fabrictype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yaka Tipi')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Materyal')),
            ],
        ),
        migrations.CreateModel(
            name='WeavingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dokuma Tipi')),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='collartype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.collertype', verbose_name='Yaka Tipi'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.materialtype', verbose_name='Materyal'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='weavingtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.weavingtype', verbose_name='Dokuma Tipi'),
        ),
    ]
