# Generated by Django 4.2.2 on 2023-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_images_product_remove_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='is_updated',
            field=models.CharField(choices=[('Güncellendi', 'Güncellendi'), ('Güncellenemedi', 'Güncellenemedi')], default='Güncellenemedi', max_length=50),
        ),
    ]
