# Generated by Django 4.2.2 on 2023-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_apiproduct_is_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='is_updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
