# Generated by Django 4.2.2 on 2023-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_apiproduct_is_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='is_updated_time',
            field=models.DateTimeField(default='0000-00-00 00:00:00', null=True),
        ),
    ]
