# Generated by Django 4.2.2 on 2023-09-24 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_apiproduct_is_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='is_updated_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
