# Generated by Django 4.2.2 on 2023-09-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_apiproduct_is_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproduct',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='apiproduct',
            name='is_updated_time',
        ),
    ]
