# Generated by Django 4.2.2 on 2023-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_remove_apiproduct_is_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='is_active',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Aktif Değil', 'Aktif Değil')], default='Aktif', max_length=50, null=True, verbose_name='Mevcut mu?'),
        ),
    ]
