# Generated by Django 4.2.2 on 2023-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_apiproduct_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='is_active',
            field=models.CharField(choices=[('1', 'Evet'), ('2', 'Hayir')], max_length=50, null=True, verbose_name='Mevcut mu?'),
        ),
    ]
