# Generated by Django 4.2.2 on 2023-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_apiproduct_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kol Tipi')),
            ],
        ),
    ]
