# Generated by Django 4.2.2 on 2023-09-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_armtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='armtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.armtype', verbose_name='Kol Tipi'),
        ),
    ]
