# Generated by Django 4.2.2 on 2023-09-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_apiproduct_armtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='description',
            field=models.CharField(max_length=355, verbose_name='Açıklama'),
        ),
    ]
