# Generated by Django 3.2.21 on 2023-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_apiproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('Modaymış Güncelleme', 'Modaymış Güncelleme')], max_length=100, null=True, verbose_name='Geçmiş Tipi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
