# Generated by Django 3.2.21 on 2023-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_updatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='updatehistory',
            name='history_type',
            field=models.CharField(choices=[('Modaymış Güncelleme', 'Modaymış Güncelleme'), ('Modaymış Aktif Olmayan Ürün', 'Modaymış Aktif Olmayan Ürün'), ('Tahtakale Güncelleme', 'Tahtakale Güncelleme'), ('Trendyol Stok&Fiyat Güncelleme', 'Trendyol Stok&Fiyat Güncelleme')], max_length=100, null=True, verbose_name='Geçmiş Tipi'),
        ),
    ]
