# Generated by Django 3.2.21 on 2023-10-27 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20231006_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ortam')),
            ],
        ),
        migrations.AlterModelOptions(
            name='updatehistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.environmenttype', verbose_name='Ortam'),
        ),
    ]
