# Generated by Django 3.2.21 on 2023-10-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_auto_20231030_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproduct',
            name='is_active',
        ),
    ]
