# Generated by Django 3.2.21 on 2023-10-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproduct',
            name='sex',
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='sextype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sex', verbose_name='Cinsiyet'),
        ),
    ]
