# Generated by Django 3.2.21 on 2023-11-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_auto_20231031_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topuk Boyu')),
            ],
        ),
        migrations.CreateModel(
            name='HeelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Topuk Tipi')),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='heelsize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.heelsize', verbose_name='Topuk Boyu'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='heeltype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.heeltype', verbose_name='Topuk Tipi'),
        ),
    ]
