# Generated by Django 3.2.21 on 2023-11-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_auto_20231104_2312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateHistory',
        ),
    ]
