# Generated by Django 3.2.21 on 2023-11-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_delete_updatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='KadinAltBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('vcreated_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Alt Beden Tablosu',
                'verbose_name_plural': 'Kadın Alt Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinAltBuyukBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('vcreated_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Alt Büyük Beden Tablosu',
                'verbose_name_plural': 'Kadın Alt Büyük Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinUstBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('boyun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyun (cm)')),
                ('gogus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Göğüs (cm)')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('vcreated_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Üst Beden Tablosu',
                'verbose_name_plural': 'Kadın Üst Beden Tablosu',
            },
        ),
        migrations.CreateModel(
            name='KadinUstBuyukBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('boyun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boyun (cm)')),
                ('gogus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Göğüs (cm)')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('vcreated_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Üst Büyük Beden Tablosu',
                'verbose_name_plural': 'Kadın Üst Büyük Beden Tablosu',
            },
        ),
    ]
