# Generated by Django 3.2.21 on 2023-11-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_kadinaltbedentablosu_kadinaltbuyukbedentablosu_kadinustbedentablosu_kadinustbuyukbedentablosu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kadinustbedentablosu',
            old_name='vcreated_at',
            new_name='created_at',
        ),
    ]
