# Generated by Django 3.2.21 on 2023-11-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_rename_vcreated_at_kadinustbedentablosu_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kadinaltbedentablosu',
            old_name='vcreated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kadinaltbuyukbedentablosu',
            old_name='vcreated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='kadinustbuyukbedentablosu',
            old_name='vcreated_at',
            new_name='created_at',
        ),
    ]
