# Generated by Django 3.2.21 on 2023-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_auto_20231127_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='kadinaltbedentablosu',
            name='eu_tr',
            field=models.IntegerField(null=True, verbose_name='EU-TR Beden'),
        ),
        migrations.AddField(
            model_name='kadinaltbuyukbedentablosu',
            name='eu_tr',
            field=models.IntegerField(null=True, verbose_name='EU-TR Beden'),
        ),
        migrations.AddField(
            model_name='kadinustbedentablosu',
            name='eu_tr',
            field=models.IntegerField(null=True, verbose_name='EU-TR Beden'),
        ),
        migrations.AddField(
            model_name='kadinustbuyukbedentablosu',
            name='eu_tr',
            field=models.IntegerField(null=True, verbose_name='EU-TR Beden'),
        ),
    ]
