# Generated by Django 3.2.21 on 2023-11-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_auto_20231127_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='KadinJeanBedenTablosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beden_adi', models.CharField(max_length=50, null=True, verbose_name='Beden Adı')),
                ('eu_tr', models.IntegerField(null=True, verbose_name='EU-TR Beden')),
                ('bel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bel (cm)')),
                ('basen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basen (cm)')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kadın Jean Beden Tablosu',
                'verbose_name_plural': 'Kadın Jean Beden Tablosu',
            },
        ),
    ]
