# Generated by Django 3.2.21 on 2023-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_kadinjeanbedentablosu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadinjeanbedentablosu',
            name='eu_tr',
            field=models.CharField(max_length=50, null=True, verbose_name='EU-TR Beden'),
        ),
    ]
