# Generated by Django 3.2.21 on 2023-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_alter_kadinjeanbedentablosu_eu_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='hepsiburada_category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Hepsiburada Kategori Numarası'),
        ),
    ]
