# Generated by Django 3.2.21 on 2023-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_apiproduct_hepsiburada_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='is_publish_hepsiburada',
            field=models.BooleanField(default=False, null=True, verbose_name='Hepsiburadada Yayında Mı?'),
        ),
    ]
