# Generated by Django 3.2.21 on 2023-12-06 18:50

from django.db import migrations, models
import django_resized.forms
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_apiproduct_is_publish_hepsiburada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKapak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapak', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to=product.models.ProductKapak.product_photo_directory_path)),
                ('modal_code', models.CharField(max_length=150, null=True, verbose_name='Model Kodu')),
            ],
        ),
    ]
