# Generated by Django 3.2.21 on 2023-12-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_productkapak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkapak',
            name='modal_code',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Model Kodu'),
        ),
    ]
