# Generated by Django 3.2.21 on 2023-12-06 20:20

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_alter_productkapak_modal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapak', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to=product.models.ProductModelGroup.product_photo_directory_path)),
                ('modal_code', models.CharField(max_length=150, null=True, unique=True, verbose_name='Model Kodu')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct')),
            ],
        ),
    ]
