# Generated by Django 3.2.21 on 2023-12-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_productmodelgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproduct',
            name='sell_count',
        ),
    ]
