# Generated by Django 3.2.21 on 2023-12-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_remove_apiproduct_sell_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodelgroup',
            old_name='modal_code',
            new_name='model_code',
        ),
    ]
