# Generated by Django 3.2.21 on 2023-12-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_alter_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiproduct',
            name='hepsiburada_price',
        ),
        migrations.RemoveField(
            model_name='apiproduct',
            name='pttavm_price',
        ),
    ]
