# Generated by Django 3.2.21 on 2023-12-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_auto_20231223_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='compatible',
            field=models.CharField(blank=True, choices=[('Alcatel Uyumlu', 'Alcatel Uyumlu'), ('Apple Uyumlu', 'Apple Uyumlu'), ('Asus Uyumlu', 'Asus Uyumlu'), ('Casper Uyumlu', 'Casper Uyumlu'), ('General Mobile Uyumlu', 'General Mobile Uyumlu'), ('Honor Uyumlu', 'Honor Uyumlu'), ('Huawei Uyumlu', 'Huawei Uyumlu'), ('Lenovo Uyumlu', 'Lenovo Uyumlu'), ('Oppo Uyumlu', 'Oppo Uyumlu'), ('POCO Uyumlu', 'POCO Uyumlu'), ('Realme Uyumlu', 'Realme Uyumlu'), ('Reeder Uyumlu', 'Reeder Uyumlu'), ('Samsung Uyumlu', 'Samsung Uyumlu'), ('TCL Uyumlu', 'TCL Uyumlu'), ('Xiaomi Uyumlu', 'Xiaomi Uyumlu')], max_length=100, null=True, verbose_name='Uyumlu Marka'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='warranty',
            field=models.CharField(choices=[('Belirtilmemiş', 'Belirtilmemiş'), ('1 Yıl', '1 Yıl'), ('2 Yıl', '2 Yıl'), ('3 Yıl', '3 Yıl'), ('4 Yıl', '4 Yıl'), ('5 Yıl', '5 Yıl'), ('6 Ay', '6 Ay')], default='Belirtilmemiş', max_length=100, null=True, verbose_name='Garanti Süresi'),
        ),
    ]
