# Generated by Django 3.2.21 on 2023-12-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_auto_20231230_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tablet Modelleri')),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='tabletmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tabletmodel', verbose_name='Elektronik Model'),
        ),
    ]
