# Generated by Django 3.2.21 on 2023-12-30 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20231230_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Uyku Modu')),
            ],
        ),
        migrations.CreateModel(
            name='TableCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kılıf Modeli')),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='casetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tablecasetype', verbose_name='Kılıf Modeli'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='sleepmode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sleepmode', verbose_name='Uyku Modu'),
        ),
    ]
