# Generated by Django 3.2.21 on 2024-01-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_auto_20231230_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='warranty',
            field=models.CharField(blank=True, choices=[('Belirtilmemiş', 'Belirtilmemiş'), ('1 Yıl', '1 Yıl'), ('2 Yıl', '2 Yıl'), ('3 Yıl', '3 Yıl'), ('4 Yıl', '4 Yıl'), ('5 Yıl', '5 Yıl'), ('6 Ay', '6 Ay')], default='Belirtilmemiş', max_length=100, null=True, verbose_name='Garanti Süresi'),
        ),
    ]
