# Generated by Django 3.2.21 on 2024-01-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_alter_apiproduct_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BijuteriTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tema/Stil')),
            ],
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='bijuteri_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.bijuteritheme', verbose_name='Tema/Stil'),
        ),
    ]
