# Generated by Django 3.2.21 on 2024-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_auto_20240115_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='ciceksepeti_discountprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Çiçeksepeti İndirimli Fiyatı'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='ciceksepeti_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Çiçeksepeti Fiyatı'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='is_ciceksepeti_discountprice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Çiçeksepeti İndirim Durumu'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='is_trendyol_discountprice',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Trendyol İndirim Durumu'),
        ),
        migrations.AddField(
            model_name='apiproduct',
            name='trendyol_discountprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol İndirimli Fiyatı'),
        ),
    ]
