# Generated by Django 3.2.21 on 2024-02-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_auto_20240204_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='trendyol_discountprice',
            field=models.FloatField(null=True, verbose_name='Trendyol İndirimli Fiyatı'),
        ),
    ]
