# Generated by Django 3.2.21 on 2024-02-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_alter_apiproduct_trendyol_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='trendyol_price',
            field=models.FloatField(null=True, verbose_name='Trendyol Fiyatı'),
        ),
    ]
