# Generated by Django 3.2.21 on 2024-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_alter_apiproduct_trendyol_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiproduct',
            name='trendyol_discountprice',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol İndirimli Fiyatı'),
        ),
        migrations.AlterField(
            model_name='apiproduct',
            name='trendyol_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Trendyol Fiyatı'),
        ),
    ]
