# Generated by Django 3.2.21 on 2024-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_auto_20240204_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproduct',
            name='is_publish_ciceksepeti',
            field=models.BooleanField(default=False, null=True, verbose_name='Çiçeksepetinde Yayında Mı?'),
        ),
    ]
