# Generated by Django 3.2.21 on 2023-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_variant_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='forward_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Vadeli Satış Değeri (KDV Dahil)'),
        ),
    ]
