# Generated by Django 3.2.21 on 2023-10-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_forward_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='forward_sale',
        ),
    ]
