# Generated by Django 3.2.21 on 2024-03-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20240329_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='useragents',
        ),
    ]
