# Generated by Django 4.2.2 on 2023-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='coupon_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kupon'),
        ),
    ]
