# Generated by Django 4.2.2 on 2023-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_coupon_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kupon'),
        ),
    ]
