# Generated by Django 4.2.2 on 2023-07-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_coupon_price_cart_coupon_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_price',
        ),
    ]
