# Generated by Django 3.2.21 on 2024-02-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trendyol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Adı')),
                ('kep', models.CharField(blank=True, max_length=255, null=True, verbose_name='KEP Adresi')),
                ('apikey', models.CharField(blank=True, max_length=255, null=True, verbose_name='Api Key')),
                ('apisecret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Api Secret')),
                ('saticiid', models.BigIntegerField(blank=True, null=True, verbose_name='Satıcı ID (Cari ID)')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('sevkiyatadresid_1', models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 1')),
                ('sevkiyatadresid_2', models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 2')),
                ('sevkiyatadresid_3', models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 3')),
                ('sevkiyatadresid_4', models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 4')),
                ('sevkiyatadresid_5', models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 5')),
                ('iadeadresid_1', models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 1')),
                ('iadeadresid_2', models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 2')),
                ('iadeadresid_3', models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 3')),
                ('iadeadresid_4', models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 4')),
                ('iadeadresid_5', models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 5')),
                ('firstbarem', models.FloatField(null=True, verbose_name='Barem 1. Aralık Maksimum Değeri')),
                ('secondbarem', models.FloatField(null=True, verbose_name='Barem 2. Aralık Maksimum Değeri')),
                ('hizmet_bedeli', models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli')),
            ],
            options={
                'verbose_name': '1) Çiçeksepeti Hesap Bilgileri',
                'verbose_name_plural': '1) Çiçeksepeti Hesap Bilgileri',
            },
        ),
    ]
