# Generated by Django 3.2.21 on 2024-03-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_is_completed_category'),
        ('ciceksepeti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciceksepetiurunler',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant', verbose_name='Ürün'),
        ),
    ]
