# Generated by Django 3.2.21 on 2024-02-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trendyol',
            new_name='Ciceksepeti',
        ),
    ]
