# Generated by Django 3.2.21 on 2024-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0002_rename_trendyol_ciceksepeti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='firstbarem',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='hizmet_bedeli',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='secondbarem',
        ),
        migrations.AddField(
            model_name='ciceksepeti',
            name='listeleme_bedeli',
            field=models.FloatField(blank=True, null=True, verbose_name='Listeleme Bedeli'),
        ),
    ]
