# Generated by Django 3.2.21 on 2024-03-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0002_alter_ciceksepetiurunler_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciceksepetiurunler',
            old_name='product',
            new_name='urun',
        ),
    ]
