# Generated by Django 3.2.21 on 2024-02-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_apiproduct_is_publish_ciceksepeti'),
        ('ciceksepeti', '0003_auto_20240202_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='apisecret',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='iadeadresid_1',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='iadeadresid_2',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='iadeadresid_3',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='iadeadresid_4',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='iadeadresid_5',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='sevkiyatadresid_1',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='sevkiyatadresid_2',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='sevkiyatadresid_3',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='sevkiyatadresid_4',
        ),
        migrations.RemoveField(
            model_name='ciceksepeti',
            name='sevkiyatadresid_5',
        ),
        migrations.CreateModel(
            name='CiceksepetiUrunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciceksepeti_kategori', models.CharField(max_length=255, null=True, verbose_name='Çiceksepeti Kategori')),
                ('yayin_durumu', models.BooleanField(default=False, verbose_name='Yayın Durumu')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': '2) Çiçeksepeti Ürünler',
                'verbose_name_plural': '2) Çiçeksepeti Ürünler',
            },
        ),
    ]
