# Generated by Django 3.2.21 on 2024-02-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0004_auto_20240213_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiceksepetiKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviye1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 1')),
                ('seviye2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 2')),
                ('seviye3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 3')),
                ('seviye4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 4')),
                ('seviye5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 5')),
                ('seviye6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 6')),
                ('seviye7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 7')),
                ('seviye8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 8')),
                ('seviye9', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 9')),
                ('seviye10', models.CharField(blank=True, max_length=255, null=True, verbose_name='Seviye 10')),
            ],
        ),
    ]
