# Generated by Django 3.2.21 on 2024-02-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0005_ciceksepetikategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye1',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye10',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye2',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye3',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye4',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye5',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye6',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye7',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye8',
        ),
        migrations.RemoveField(
            model_name='ciceksepetikategori',
            name='seviye9',
        ),
        migrations.AddField(
            model_name='ciceksepetikategori',
            name='category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Kategori ID'),
        ),
        migrations.AddField(
            model_name='ciceksepetikategori',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='ciceksepetikategori',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ciceksepeti.ciceksepetikategori', verbose_name='Kaegori Adı'),
        ),
    ]
