# Generated by Django 3.2.21 on 2024-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0006_auto_20240213_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciceksepetikategori',
            name='parentCategoryId',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Parent Kategori ID'),
        ),
    ]
