# Generated by Django 3.2.21 on 2024-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0008_alter_ciceksepetikategori_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciceksepetiurunler',
            name='ciceksepeti_kategori_id',
            field=models.BigIntegerField(null=True, verbose_name='Çiceksepeti Kategori ID'),
        ),
        migrations.DeleteModel(
            name='CiceksepetiKategori',
        ),
    ]
