# Generated by Django 3.2.21 on 2024-02-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0009_auto_20240213_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciceksepetiurunler',
            name='ciceksepeti_kategori',
        ),
    ]
