# Generated by Django 3.2.21 on 2024-02-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0011_trendyolorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrendyolOrders',
            new_name='CiceksepetiOrders',
        ),
    ]
