# Generated by Django 3.2.21 on 2024-02-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciceksepeti', '0012_rename_trendyolorders_ciceksepetiorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciceksepetiorders',
            options={'ordering': ['-order_date'], 'verbose_name': '3) Çiçeksepeti Siparişler', 'verbose_name_plural': '3) Çiçeksepeti Siparişler'},
        ),
    ]
