# Generated by Django 3.2.21 on 2024-01-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hepsiburada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolMoreProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, null=True, verbose_name='Sipariş Numarası')),
                ('packet_number', models.CharField(max_length=255, null=True, verbose_name='Paket Numarası')),
                ('quantity', models.BigIntegerField(null=True, verbose_name='Adet')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=100, null=True, verbose_name='Barkod')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beden')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('unit_price', models.FloatField(null=True, verbose_name='Birim Fiyat')),
                ('sales_amount', models.FloatField(null=True, verbose_name='Satış Tutarı')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('İade Edildi', 'İade Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı'), ('Birden Fazla', 'Birden Fazla')], max_length=255, null=True, verbose_name='Durum')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
