# Generated by Django 3.2.21 on 2024-01-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hepsiburada', '0002_trendyolmoreproductorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='hepsiburadasiparisler',
            name='process_price',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Bedeli'),
        ),
    ]
