# Generated by Django 3.2.21 on 2024-01-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hepsiburada', '0003_hepsiburadasiparisler_process_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrendyolMoreProductOrder',
            new_name='HepsiburadaMoreProductOrder',
        ),
    ]
