# Generated by Django 3.2.21 on 2024-01-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240107_0511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='BlogKeywords',
        ),
    ]
