from django.urls import path
from adminpage.views import *

urlpatterns = [
    path('giris-yap/', admin_login, name='admin_login'),

    path('', mainpage, name='admin_mainpage'),
    path('sliders/', slider, name='admin_slider'),
    path('sliders/id=<int:id>/', slider_detail, name='admin_slider_detail'),
    path('sliders/sil/id=<int:id>/', slider_delete, name='admin_slider_delete'),
    path('sliders/tumunu-sil/', slider_delete_all, name='admin_slider_delete_all'),
    path('sliders/secili-slider-sil/', slider_select_delete,
         name='slider_select_delete'),
    path('sliders/yayina-al/id=<int:id>/', slider_publish, name='admin_slider_publish'),
    path('sliders/yayinadan-kaldir/id=<int:id>/', slider_not_publish, name='admin_slider_not_publish'),
    path('bildirimler/', notification, name='notification'),
    path('bildirimler/id=<int:id>/', read_notification, name='read_notification'),
    path('bildirimler/sil/id=<int:id>/', sil_notification, name='sil_notification'),
    path('bildirimler/secili-sil/', secili_sil_notification, name='secili_sil_notification'),
    path('sayfalar/hakkimizda/', admin_aboutus, name='admin_aboutus'),
    path('sayfalar/anasayfa/', page_mainpage, name='page_mainpage'),
    path('kullanicilar/', kullanicilar, name='kullanicilar'),
    path('kullanicilar/kullanici-goruntule/kullanici_id=<int:id>/', kullanici_goruntule, name='kullanici_goruntule'),
    path('kullanicilar/kullanici-sil/kullanici_id=<int:id>/', kullanici_sil, name='kullanici_sil'),
    path('kategoriler/birinci-seviye-kategoriler/', kategoriler_seviye1, name='kategoriler_seviye1'),
    path('kategoriler/birinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye1_guncelle,
         name='kategoriler_seviye1_guncelle'),
    path('kategoriler/birinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye1_sil,
         name='kategoriler_seviye1_sil'),
    path('kategoriler/birinci-seviye-kategoriler/hepsini-sil/', kategoriler_seviye1_hepsini_sil,
         name='kategoriler_seviye1_hepsini_sil'),
    path('kategoriler/birinci-seviye-kategoriler/export-excel/', kategoriler_seviye1_export_excel,
         name='kategoriler_seviye1_export_excel'),
    path('kategoriler/birinci-seviye-kategoriler/export-pdf/', kategoriler_seviye1_export_pdf,
         name='kategoriler_seviye1_export_pdf'),
    path('kategoriler/ikinci-seviye-kategoriler/<slug>-alt-kategorileri/', kategoriler_seviye2,
         name='kategoriler_seviye2'),
    path('kategoriler/ikinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye2_guncelle,
         name='kategoriler_seviye2_guncelle'),
    path('kategoriler/ikinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye2_sil,
         name='kategoriler_seviye2_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye2_export_excel,
         name='kategoriler_seviye2_export_excel'),
    path('kategoriler/ikinci-seviye-kategoriler/export-excel/', kategoriler_seviye2_hepsi_export_excel,
         name='kategoriler_seviye2_hepsi_export_excel'),
    path('kategoriler/ikinci-seviye-kategoriler/<slug>/hepsini-sil/', kategoriler_seviye2_hepsini_sil,
         name='kategoriler_seviye2_hepsini_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/tum-alt-kategorileri-sil/', kategoriler_seviye2_tum_sil,
         name='kategoriler_seviye2_tum_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/secili-kategori-sil/', kategoriler2_secilileri_sil,
         name='kategoriler2_secilileri_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/',
         kategoriler_seviye3, name='kategoriler_seviye3'),
    path(
        'kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/guncelle/',
        kategoriler_seviye3_guncelle,
        name='kategoriler_seviye3_guncelle'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/sil/',
         kategoriler_seviye3_sil,
         name='kategoriler_seviye3_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye3_export_excel,
         name='kategoriler_seviye3_export_excel'),
    path('kategoriler/ucuncu-seviye-kategoriler/export-excel/', kategoriler_seviye3_hepsi_export_excel,
         name='kategoriler_seviye3_hepsi_export_excel'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/hepsini-sil/',
         kategoriler_seviye3_hepsini_sil,
         name='kategoriler_seviye3_hepsini_sil'),
    path(
        'kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/tum-alt-kategorileri-sil/',
        kategoriler_seviye3_tum_sil,
        name='kategoriler_seviye3_tum_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/secili-kategori-sil/', kategoriler3_secilileri_sil,
         name='kategoriler3_secilileri_sil'),
    path('kategoriler/secili-kategori-sil/', kategoriler_secilileri_sil, name='kategoriler_secilileri_sil'),
    path('urunler/', products, name='admin_product'),
    path('urunler/sil/json/', ajax_select_delete_product, name='ajax_select_delete_product'),
    path('urunler/sil/', all_delete_product, name='all_delete_product'),
    path('urunler/urun_id=<int:id>/', product_detail, name='product_detail'),
    path('urunler/kampanyali-urunlar/', kampanyali_urunler, name='kampanyali_urunler'),
    path('urunler/excel-indir/', product_export_excel, name='product_export_excel'),
    path('urunler/ozellik-guncelleme/', urun_ozellik_guncelleme, name='urun_ozellik_guncelleme'),
    path('siparis-yonetimi/siparisler/', orders, name='admin_orders'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/', order_detail, name='admin_order_detail'),
    path('siparis-yonetimi/siparisler/sil/siparis_no=<str:order_number>/', order_delete, name='admin_order_delete'),
    path('siparis-yonetimi/iptal-talepleri/', iptal_talepleri, name='admin_iptal_talepleri'),
    path('siparis-yonetimi/iade-talepleri/', iade_talepleri, name='iade_talepleri'),
    path('siparis-yonetimi/iade-talepleri/siparis_no=<str:order_number>/<int:product_id>/', iade_talepleri_detay,
         name='iade_talepleri_detay'),

    path('xml-yonetimi/tahtakale/veri-yukle-guncelle/', tahtakale_product, name="tahtakale_product"),
    path('xml-yonetimi/tahtakale/veri-yukle/', tahtakale_product_load, name="tahtakale_product_load"),
    path('xml-yonetimi/tahtakale/veri-guncelle/', tahtakale_product_update, name="tahtakale_product_update"),
    path('xml-yonetimi/haydigiy/veri-yukle-guncelle/', haydigiy_product, name="haydigiy_product"),
    path('xml-yonetimi/haydigiy/veri-yukle/', haydigiy_product_load, name="haydigiy_product_load"),
    path('xml-yonetimi/haydigiy/veri-guncelle/', haydigiy_product_update, name="haydigiy_product_update"),
    path('xml-yonetimi/haydigiy/aktif-olmayan-urunler/', haydigiy_find_not_active_product_page,
         name="haydigiy_find_not_active_product_page"),
    path('xml-yonetimi/haydigiy/aktif-olmayan-urunleri-bul/', haydigiy_find_not_active_product,
         name="haydigiy_find_not_active_product"),

    # trendyol
    path('trendyol/hesap-bilgileri/', trendyol_hesap_bilgileri_ekle, name="trendyol_hesap_bilgileri_ekle"),
    path('trendyol/urun-giris/', trendyol_add_product, name="trendyol_add_product"),
    path('trendyol/urun-giris/giyim/', trendyol_add_product_giyim, name="trendyol_add_product_giyim"),
    path('trendyol/urun-giris/giyim/kategori_no=<category_no>/', trendyol_add_product_giyim_category1,
         name="trendyol_add_product_giyim_category1"),
    path('trendyol/urun-giris/giyim/kategori_id=<int:id>/trendyol/urun-gonder/',
         trendyol_add_product_giyim_send_trendyol, name="trendyol_add_product_giyim_send_trendyol"),
    path('trendyol/stok-fiyat-guncelleme/', trendyol_update_price_stok, name="trendyol_update_price_stok"),
    path('trendyol/bilgi-guncelleme/', trendyol_update_product, name="trendyol_update_product"),
    path('trendyol/urun-silme/', trendyol_delete_product, name="trendyol_delete_product"),
    path('trendyol/urunler/', trendyol_products, name="trendyol_products"),
    path('trendyol/siparis-ekle/', trendyol_add_order, name='trendyol_add_order'),
    path('trendyol/servis-istekleri/', trendyol_batch_request, name="trendyol_batch_request"),
    path('trendyol/servis-istekleri/goruntule/<str:batch_request>/', trendyol_batch_request_detail,
         name="trendyol_batch_request_detail"),
    path('trendyol/servis-istekleri/sil/<int:id>/', trendyol_batch_request_delete,
         name="trendyol_batch_request_delete"),
    path('trendyol/servis-istekleri/tumuunu-sil/', trendyol_batch_request_delete_all,
         name="trendyol_batch_request_delete_all"),

    # muhasebe
    path('kesilen-faturalar/fatura-ekle/', kesilen_fatura_ekle, name="kesilen_fatura_ekle"),
    path('kesilen-faturalar/tum-faturalar/', kesilen_faturalar, name="kesilen_faturalar"),
    path('kesilen-faturalar/tum-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_kesilen_fatura,
         name="update_kesilen_fatura"),
    path('kesilen-faturalar/tum-faturalar/fatura-sil/fatura_id=<int:id>/', delete_kesilen_fatura,
         name="delete_kesilen_fatura"),
    path('kesilen-faturalar/tum-faturalar/excel/', kesilen_faturalar_export_excel,
         name="kesilen_faturalar_export_excel"),

    path('alinan-faturalar/fatura-ekle/', alinan_fatura_ekle, name="alinan_fatura_ekle"),
    path('alinan-faturalar/tum-faturalar/', alinan_faturalar, name="alinan_faturalar"),
    path('alinan-faturalar/tum-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_alinan_fatura,
         name="update_alinan_fatura"),
    path('alinan-faturalar/tum-faturalar/fatura-sil/fatura_id=<int:id>/', delete_alinan_fatura,
         name="delete_alinan_fatura"),
    path('alinan-faturalar/tum-faturalar/excel/', alinan_faturalar_export_excel,
         name="alinan_faturalar_export_excel"),

    path('hesap-bilgilerim/', user_info, name='user_info'),
    path('sifre-degistir/', change_password, name='admin_change_password'),
    path('gecmis-kayitlar/guncelleme-gecmisi/', update_history, name='update_history'),
    path('gecmis-kayitlar/guncelleme-gecmisi/tumunu-sil/', update_history_all_delete, name='update_history_all_delete'),
    path('gecmis-kayitlar/guncelleme-gecmisi/sil/id=<int:id>/', update_history_delete, name='update_history_delete'),
]
