from django.urls import path
from adminpage.views import *

urlpatterns = [
    path('giris-yap/', admin_login, name='admin_login'),

    path('', mainpage, name='admin_mainpage'),
    path('kategoriler/birinci-seviye-kategoriler/', kategoriler_seviye1, name='kategoriler_seviye1'),
    path('kategoriler/birinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye1_guncelle,
         name='kategoriler_seviye1_guncelle'),
    path('kategoriler/birinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye1_sil,
         name='kategoriler_seviye1_sil'),
    path('kategoriler/birinci-seviye-kategoriler/hepsini-sil/', kategoriler_seviye1_hepsini_sil,
         name='kategoriler_seviye1_hepsini_sil'),
    path('kategoriler/birinci-seviye-kategoriler/export-excel/', kategoriler_seviye1_export_excel,
         name='kategoriler_seviye1_export_excel'),
    path('kategoriler/birinci-seviye-kategoriler/export-pdf/', kategoriler_seviye1_export_pdf,
         name='kategoriler_seviye1_export_pdf'),
    path('kategoriler/ikinci-seviye-kategoriler/<slug>-alt-kategorileri/', kategoriler_seviye2,
         name='kategoriler_seviye2'),
    path('kategoriler/ikinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye2_guncelle,
         name='kategoriler_seviye2_guncelle'),
    path('kategoriler/ikinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye2_sil,
         name='kategoriler_seviye2_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye2_export_excel,
         name='kategoriler_seviye2_export_excel'),
    path('kategoriler/ikinci-seviye-kategoriler/export-excel/', kategoriler_seviye2_hepsi_export_excel,
         name='kategoriler_seviye2_hepsi_export_excel'),
    path('kategoriler/ikinci-seviye-kategoriler/<slug>/hepsini-sil/', kategoriler_seviye2_hepsini_sil,
         name='kategoriler_seviye2_hepsini_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/tum-alt-kategorileri-sil/', kategoriler_seviye2_tum_sil,
         name='kategoriler_seviye2_tum_sil'),
    path('kategoriler/ikinci-seviye-kategoriler/secili-kategori-sil/', kategoriler2_secilileri_sil,
         name='kategoriler2_secilileri_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/',
         kategoriler_seviye3, name='kategoriler_seviye3'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/guncelle/', kategoriler_seviye3_guncelle,
         name='kategoriler_seviye3_guncelle'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/sil/', kategoriler_seviye3_sil,
         name='kategoriler_seviye3_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye3_export_excel,
         name='kategoriler_seviye3_export_excel'),
    path('kategoriler/ucuncu-seviye-kategoriler/export-excel/', kategoriler_seviye3_hepsi_export_excel,
         name='kategoriler_seviye3_hepsi_export_excel'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/hepsini-sil/', kategoriler_seviye3_hepsini_sil,
         name='kategoriler_seviye3_hepsini_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/tum-alt-kategorileri-sil/', kategoriler_seviye3_tum_sil,
         name='kategoriler_seviye3_tum_sil'),
    path('kategoriler/ucuncu-seviye-kategoriler/secili-kategori-sil/', kategoriler3_secilileri_sil,
         name='kategoriler3_secilileri_sil'),
    path('kategoriler/secili-kategori-sil/', kategoriler_secilileri_sil, name='kategoriler_secilileri_sil'),
    path('urunler/', products, name='admin_product'),

    path('xml-yonetimi/tahtakale/veri-yukle-guncelle/', tahtakale_product, name="tahtakale_product"),
    path('xml-yonetimi/tahtakale/veri-yukle/', tahtakale_product_load, name="tahtakale_product_load"),
    path('xml-yonetimi/tahtakale/veri-guncelle/', tahtakale_product_update, name="tahtakale_product_update"),
    path('xml-yonetimi/haydigiy/veri-yukle-guncelle/', haydigiy_product, name="haydigiy_product"),
    path('xml-yonetimi/haydigiy/veri-yukle/', haydigiy_product_load, name="haydigiy_product_load"),
    path('xml-yonetimi/haydigiy/veri-guncelle/', haydigiy_product_update, name="haydigiy_product_update"),

    # trendyol
    path('trendyol/hesap-bilgileri/', trendyol_hesap_bilgileri_ekle, name="trendyol_hesap_bilgileri_ekle"),
    path('trendyol/urun-giris/', trendyol_add_product, name="trendyol_add_product"),
    path('trendyol/urun-giris/giyim/', trendyol_add_product_giyim, name="trendyol_add_product_giyim"),
    path('trendyol/urun-giris/giyim/kategori_no=<category_no>/', trendyol_add_product_giyim_category1,
         name="trendyol_add_product_giyim_category1"),
    path('trendyol/urun-giris/giyim/kategori_id=<int:id>/trendyol/urun-gonder/',
         trendyol_add_product_giyim_send_trendyol, name="trendyol_add_product_giyim_send_trendyol"),
    path('trendyol/stok-fiyat-guncelleme/', trendyol_update_price_stok, name="trendyol_update_price_stok"),

    # muhasebe
    path('kesilen-faturalar/fatura-ekle/', kesilen_fatura_ekle, name="kesilen_fatura_ekle"),
    path('kesilen-faturalar/tum-faturalar/', kesilen_faturalar, name="kesilen_faturalar"),
    path('kesilen-faturalar/tum-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_kesilen_fatura,
         name="update_kesilen_fatura"),
    path('kesilen-faturalar/tum-faturalar/fatura-sil/fatura_id=<int:id>/', delete_kesilen_fatura,
         name="delete_kesilen_fatura"),
    path('kesilen-faturalar/tum-faturalar/excel/', kesilen_faturalar_export_excel,
         name="kesilen_faturalar_export_excel"),

    path('alinan-faturalar/fatura-ekle/', alinan_fatura_ekle, name="alinan_fatura_ekle"),
    path('alinan-faturalar/tum-faturalar/', alinan_faturalar, name="alinan_faturalar"),
    path('alinan-faturalar/tum-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_alinan_fatura,
         name="update_alinan_fatura"),
    path('alinan-faturalar/tum-faturalar/fatura-sil/fatura_id=<int:id>/', delete_alinan_fatura,
         name="delete_alinan_fatura"),
    path('alinan-faturalar/tum-faturalar/excel/', alinan_faturalar_export_excel,
         name="alinan_faturalar_export_excel"),

    path('hesap-bilgilerim/', user_info, name='user_info'),
    path('sifre-degistir/', change_password, name='admin_change_password'),
]
