from django.urls import path
from adminpage.views import *
from ciceksepeti.views import *

urlpatterns = [
    path('giris-yap/', admin_login, name='admin_login'),

    path('', mainpage, name='admin_mainpage'),
    path('siparis-istatistikleri-ajax', siparis_istatistikleri, name='siparis_istatistikleri'),
    path('platform-istatistikleri-ajax', platform_istatistikleri, name='platform_istatistikleri'),
    path('fatura-istatistikleri-ajax', fatura_istatistikleri, name='fatura_istatistikleri'),
    path('kar-istatistikleri-ajax', aylik_kar, name='aylik_kar'),
    path('bildirimler/id=<int:id>/', read_notification, name='read_notification'),
    path('bildirimler/sil/id=<int:id>/', sil_notification, name='sil_notification'),
    path('bildirimler/secili-sil/', secili_sil_notification, name='secili_sil_notification'),

    ##Site Yonetimi
    path('site-yonetimi/site-ayarlari/', site_ayarlari, name='site_ayarlari'),
    path('site-yonetimi/hakkimizda/', admin_aboutus, name='admin_aboutus'),
    path('site-yonetimi/anasayfa/', page_mainpage, name='page_mainpage'),
    path('site-yonetimi/banner/hepsini-sil/', banner_hepsini_sil,
         name='banner_hepsini_sil'),
    path('site-yonetimi/banner/export-excel/', banner_export_excel,
         name='banner_export_excel'),
    path('site-yonetimi/banner/secili-harcama-sil/', banner_secilileri_sil,
         name='banner_secilileri_sil'),
    path('site-yonetimi/banner/secili-banner/id=<int:id>/goruntulenme-yukselt/', banner_plus_view,
         name='banner_plus_view'),
    path('site-yonetimi/banner/secili-banner/id=<int:id>/yayin-durumu-degistir/', banner_publish,
         name='banner_publish'),
    path('site-yonetimi/banner/secili-banner/id=<int:id>/sira-degistir/', banner_order,
         name='banner_order'),
    path('site-yonetimi/banner/secili-banner/id=<int:id>/gidecegi-url-degistir/', banner_url,
         name='banner_url'),
    path('site-yonetimi/header-cat/hepsini-sil/', headercat_hepsini_sil,
         name='headercat_hepsini_sil'),
    path('site-yonetimi/headercat/secili-headercat-sil/', headercat_secilileri_sil,
         name='headercat_secilileri_sil'),
    path('site-yonetimi/headercat/secili-headercat/id=<int:id>/yayin-durumu-degistir/', headercat_publish,
         name='headercat_publish'),
    path('site-yonetimi/headercat/secili-headercat/id=<int:id>/sira-degistir/', headercat_order,
         name='headercat_order'),
    path('site-yonetimi/headercat/secili-headercat/id=<int:id>/gidecegi-url-degistir/', cat_url,
         name='cat_url'),
    path('site-yonetimi/musteri-sorulari/', musteri_sorulari, name='musteri_sorulari'),
    path('site-yonetimi/musteri-sorulari/soru-cevapla/soru_id=<int:id>/', musteri_sorulari_cevapla,
         name='musteri_sorulari_cevapla'),

    ## Blok Yonetimi
    path('blog-yonetimi/kategoriler/', blog_kategori, name='blog_kategori'),
    path('blog-yonetimi/kategoriler/guncelle/kategori_id=<int:id>/', blog_kategori_guncelle, name='blog_kategori_guncelle'),
    path('blog-yonetimi/kategoriler/id=<int:id>/sil/', blog_kategori_sil,
         name='blog_kategori_sil'),
    path('blog-yonetimi/kategoriler/hepsini-sil/', blog_kategori_hepsini_sil,
         name='blog_kategori_hepsini_sil'),
    path('blog-yonetimi/kategoriler/export-excel/', blog_kategori_export_excel,
         name='blog_kategori_export_excel'),
    path('blog-yonetimi/kategoriler/secili-kategori-sil/', blog_kategori_secilileri_sil,
         name='blog_kategori_secilileri_sil'),
    path('blog-yonetimi/blog-yazilari/', blog_yazilari, name='blog_yazilari'),
    path('blog-yonetimi/blog-yazilari/blog-ekle/', blog_ekle, name='blog_ekle'),


    ## Kampanya Yönetimi
    path('kampanya-yonetimi/kampanyalar/', kampanyalar, name='kampanyalar'),
    path('kampanya-yonetimi/kampanyalar/kampanya=<str:slug>/urun-ekle/', kampanya_urun_ekle, name='kampanya_urun_ekle'),
    path('kampanya-yonetimi/kampanyalar/hepsini-sil/', kampanya_hepsini_sil,
         name='kampanya_hepsini_sil'),
    path('kampanya-yonetimi/kampanyalar/export-excel/', kampanya_export_excel,
         name='kampanya_export_excel'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanyalari-sil/', kampanya_secilileri_sil,
         name='kampanya_secilileri_sil'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanya/id=<int:id>/yayin-durumu-degistir/', kampanya_publish,
         name='kampanya_publish'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanya/id=<int:kampanya_id>/urun-sec/', kampanya_urun_sec,
         name='kampanya_urun_sec'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanya/id=<int:kampanya_id>/urun-kaldir/', kampanya_urun_kaldir,
         name='kampanya_urun_kaldir'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanya/id=<int:kampanya_id>/secili-urunler/', kampanya_secili_urunler,
         name='kampanya_secili_urunler'),
    path('kampanya-yonetimi/kampanyalar/secili-kampanya/id=<int:kampanya_id>/secili-urunler/excel-indir/',
         kampanya_secili_urunler_excel,
         name='kampanya_secili_urunler_excel'),

    ##Kullanıcı Yönetimi
    path('kullanici-yonetimi/kullanicilar/', kullanicilar, name='kullanicilar'),
    path('kullanici-yonetimi/kullanicilar/kullanici-goruntule/kullanici_id=<int:id>/', kullanici_goruntule,
         name='kullanici_goruntule'),
    path('kullanicilar/kullanici-sil/kullanici_id=<int:id>/', kullanici_sil, name='kullanici_sil'),
    path('kullanici-yonetimi/kullanici-islemleri/kullanici-yetkilendir/kullanici_id=<int:id>/', kullanici_izinleri,
         name='kullanici_izinleri'),
    path('kullanici-yonetimi/gorevler/', gorevler, name='gorevler'),
    path('kullanici-yonetimi/gorevler/gorev-ekle/', gorev_ekle, name='gorev_ekle'),
    path('kullanici-yonetimi/gorevler/kullanici-gorevlendir/', kullanici_gorevlendir, name='kullanici_gorevlendir'),
    path('kullanici-yonetimi/gorevler/gorev-detay/gorev_id=<int:id>/', gorev_detay, name='gorev_detay'),
    path('kullanici-yonetimi/gorevler/gorev-sil/gorev_id=<int:id>/', gorev_sil, name='gorev_sil'),
    path('kullanici-yonetimi/gorevler/gorev-yapilma-durumu/', gorev_yapilma_durumu, name='gorev_yapilma_durumu'),

    ##Kategori Yönetimi
    path('kategori-yonetimi/birinci-seviye-kategoriler/', kategoriler_seviye1, name='kategoriler_seviye1'),
    path('kategori-yonetimi/birinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye1_guncelle,
         name='kategoriler_seviye1_guncelle'),
    path('kategori-yonetimi/birinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye1_sil,
         name='kategoriler_seviye1_sil'),
    path('kategori-yonetimi/birinci-seviye-kategoriler/hepsini-sil/', kategoriler_seviye1_hepsini_sil,
         name='kategoriler_seviye1_hepsini_sil'),
    path('kategori-yonetimi/birinci-seviye-kategoriler/export-excel/', kategoriler_seviye1_export_excel,
         name='kategoriler_seviye1_export_excel'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/<slug>-alt-kategorileri/', kategoriler_seviye2,
         name='kategoriler_seviye2'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/id=<int:id>/guncelle/', kategoriler_seviye2_guncelle,
         name='kategoriler_seviye2_guncelle'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/id=<int:id>/sil/', kategoriler_seviye2_sil,
         name='kategoriler_seviye2_sil'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye2_export_excel,
         name='kategoriler_seviye2_export_excel'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/<slug>/hepsini-sil/', kategoriler_seviye2_hepsini_sil,
         name='kategoriler_seviye2_hepsini_sil'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/tum-alt-kategorileri-sil/', kategoriler_seviye2_tum_sil,
         name='kategoriler_seviye2_tum_sil'),
    path('kategori-yonetimi/ikinci-seviye-kategoriler/secili-kategori-sil/', kategoriler2_secilileri_sil,
         name='kategoriler2_secilileri_sil'),
    path('kategori-yonetimi/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/',
         kategoriler_seviye3, name='kategoriler_seviye3'),
    path(
        'kategori-yonetimi/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/guncelle/',
        kategoriler_seviye3_guncelle,
        name='kategoriler_seviye3_guncelle'),
    path(
        'kategori-yonetimi/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/id=<int:id>/sil/',
        kategoriler_seviye3_sil,
        name='kategoriler_seviye3_sil'),
    path('kategori-yonetimi/ucuncu-seviye-kategoriler/export-excel/<slug>/', kategoriler_seviye3_export_excel,
         name='kategoriler_seviye3_export_excel'),
    path('kategori-yonetimi/ucuncu-seviye-kategoriler/export-excel/', kategoriler_seviye3_hepsi_export_excel,
         name='kategoriler_seviye3_hepsi_export_excel'),
    path(
        'kategori-yonetimi/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/hepsini-sil/',
        kategoriler_seviye3_hepsini_sil,
        name='kategoriler_seviye3_hepsini_sil'),
    path(
        'kategori-yonetimi/ucuncu-seviye-kategoriler/<main_slug>-ana-kategori/<sub_slug>-alt-kategorileri/tum-alt-kategorileri-sil/',
        kategoriler_seviye3_tum_sil,
        name='kategoriler_seviye3_tum_sil'),
    path('kategori-yonetimi/ucuncu-seviye-kategoriler/secili-kategori-sil/', kategoriler3_secilileri_sil,
         name='kategoriler3_secilileri_sil'),
    path('kategori-yonetimi/secili-kategori-sil/', kategoriler_secilileri_sil, name='kategoriler_secilileri_sil'),

    ## Urun Yonetimi

    path('urunler/tum-urunler/', products, name='admin_product'),
    path('urunler/sil/json/', ajax_select_delete_product, name='ajax_select_delete_product'),
    path('urunler/sil/', all_delete_product, name='all_delete_product'),
    path('urunler/aktif-olmayan-urunler/sil/', not_active_product_delete, name='not_active_product_delete'),
    path('urunler/tum-urunler/barkod=<str:barkod>/', product_detail, name='product_detail'),
    path('urunler/excel-indir/', product_export_excel, name='product_export_excel'),
    path('urunler/urun-islemleri/', urun_islemleri, name='urun_islemleri'),
    path('urunler/ozellik-guncelleme/', urun_ozellik_guncelleme, name='urun_ozellik_guncelleme'),
    path('urunler/beden-tablosu/', beden_tablosu, name='beden_tablosu'),
    path('urunler/beden-tablosu/kadin-ust-beden-tablosu/id=<int:id>/sil/', kadin_ust_beden_sil,
         name='kadin_ust_beden_sil'),
    path('urunler/beden-tablosu/kadin-ust-buyuk-beden-tablosu/id=<int:id>/sil/', kadin_ust_buyuk_beden_sil,
         name='kadin_ust_buyuk_beden_sil'),
    path('urunler/beden-tablosu/kadin-alt-beden-tablosu/id=<int:id>/sil/', kadin_alt_beden_sil,
         name='kadin_alt_beden_sil'),
    path('urunler/beden-tablosu/kadin-alt-buyuk-beden-tablosu/id=<int:id>/sil/', kadin_alt_buyuk_beden_sil,
         name='kadin_alt_buyuk_beden_sil'),
    path('urunler/beden-tablosu/kadin-jean-beden-tablosu/id=<int:id>/sil/', kadin_jean_beden_sil,
         name='kadin_jean_beden_sil'),
    path('urunler/kategori-degistir/', kategori_degistir, name='kategori_degistir'),
    path('urunler/kategorisi-hatali-urunler/', kategori_hatasi_bulunan_urunler, name='kategori_hatasi_bulunan_urunler'),
    path('urunler/kategorisi-hatali-urunler/kategori-duzelt/', kategori_guncelle, name='kategori_guncelle'),

    ## Siparis Yonetimi
    path('siparis-yonetimi/tum-siparisler/', siparisler, name='admin_siparisler'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/', order_detail, name='admin_order_detail'),
    path('siparis-yonetimi/trendyol-siparisler/id=<int:id>/', trendyol_order_detail, name='trendyol_order_detail'),
    path('siparis-yonetimi/hepsiburada-siparisler/id=<int:id>/', hepsiburada_order_detail, name='hepsiburada_order_detail'),
    path('siparis-yonetimi/trendyol-siparisler/siparisleri-getir/', get_trendyol_orders, name='get_trendyol_orders'),
    path('siparis-yonetimi/hepsiburada-siparisler/siparis-ekle/', hepsiburada_siparis_ekle, name='hepsiburada_siparis_ekle'),
    path('siparis-yonetimi/siparisler/sil/siparis_no=<str:order_number>/', order_delete, name='admin_order_delete'),
    path('siparis-yonetimi/trendyol-siparisler/sil/id=<int:id>/', trendyol_order_delete, name='trendyol_order_delete'),
    path('siparis-yonetimi/iptal-talepleri/', iptal_talepleri, name='admin_iptal_talepleri'),
    path('siparis-yonetimi/iade-talepleri/', iade_talepleri, name='iade_talepleri'),
    path('siparis-yonetimi/iade-talepleri/siparis_no=<str:order_number>/<int:product_id>/', iade_talepleri_detay,
         name='iade_talepleri_detay'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/isleme-al/', order_isleme_al,
         name='order_isleme_al'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/kargo-bildir/', order_kargo_bildir,
         name='order_kargo_bildir'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/siparis-tamamla/', order_tamamla,
         name='order_tamamla'),
    path('siparis-yonetimi/siparisler/siparis_no=<str:order_number>/mail-gonder/', order_mail_gonder,
         name='order_mail_gonder'),
    path('siparis-yonetimi/siparisler/durum-guncelle/', change_order_status,
         name='change_order_status'),

    path('xml-yonetimi/haydigiy/veri-yukle-guncelle/', haydigiy_product, name="haydigiy_product"),
    path('xml-yonetimi/haydigiy/veri-yukle/', haydigiy_product_load, name="haydigiy_product_load"),
    path('xml-yonetimi/haydigiy/veri-guncelle/', haydigiy_product_update, name="haydigiy_product_update"),
    path('xml-yonetimi/haydigiy/veri-grupla/', haydigiy_gruplama, name="haydigiy_gruplama"),
    path('xml-yonetimi/haydigiy/aktif-olmayan-urunleri-bul/', haydigiy_find_not_active_product,
         name="haydigiy_find_not_active_product"),
    path('xml-yonetimi/xml-dunyasi/veri-yukle-guncelle/', xmldunyasi_product, name="xmldunyasi_product"),
    path('xml-yonetimi/xml-dunyasi/veri-yukle/', xmldunyasi_product_load, name="xmldunyasi_product_load"),
    path('xml-yonetimi/xml-dunyasi/veri-guncelle/', xmldunyasi_product_update, name="xmldunyasi_product_update"),
    path('xml-yonetimi/xml-dunyasi/veri-grupla/', xmldunyasi_gruplama, name="xmldunyasi_gruplama"),
    path('xml-yonetimi/xml-dunyasi/aktif-olmayan-urunleri-bul/', xmldunyasi_find_not_active_product,
         name="xmldunyasi_find_not_active_product"),
    path('xml-yonetimi/xml-dunyasi/bijuteri/veri-yukle-guncelle/', xmldunyasi_bijuteri_product_load, name="xmldunyasi_bijuteri_product_load"),
    path('xml-yonetimi/xml-dunyasi/bijuteri/veri-guncelle/', xmldunyasi_bijuteri_product_update, name="xmldunyasi_bijuteri_product_update"),
    path('xml-yonetimi/fiyat-ayarla/', xml_fiyat_ayarla, name="xml_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/tredyshop-fiyat-ayarla/', TredyShopFiyatAyarlaCreate.as_view(),
         name="tredyshop_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/tredyshop-fiyat-guncelle/<int:pk>/', TredyShopFiyatAyarlaUpdate.as_view(),
         name="tredyshop_fiyat_guncelle"),
    path('xml-yonetimi/fiyat-ayarla/tredyshop-fiyat-sil/<int:pk>/', delete_tredyshop_karmarji_formset,
         name="tredyshop_fiyat_delete"),
    path('xml-yonetimi/fiyat-ayarla/trendyol-fiyat-ayarla/', TrendyolFiyatAyarlaCreate.as_view(),
         name="trendyol_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/trendyol-fiyat-guncelle/<int:pk>/', TrendyolFiyatAyarlaUpdate.as_view(),
         name="trendyol_fiyat_guncelle"),
    path('xml-yonetimi/fiyat-ayarla/trendyol-fiyat-sil/<int:pk>/', delete_trendyol_karmarji_formset,
         name="trendyol_fiyat_delete"),
    path('xml-yonetimi/fiyat-ayarla/hepsiburada-fiyat-ayarla/', HepsiburadaFiyatAyarlaCreate.as_view(),
         name="hepsiburada_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/hepsiburada-fiyat-guncelle/<int:pk>/', HepsiburadaFiyatAyarlaUpdate.as_view(),
         name="hepsiburada_fiyat_guncelle"),
    path('xml-yonetimi/fiyat-ayarla/hepsiburada-fiyat-sil/<int:pk>/', delete_hepsiburada_karmarji_formset,
         name="hepsiburada_fiyat_delete"),
    path('xml-yonetimi/fiyat-ayarla/ciceksepeti-fiyat-ayarla/', CiceksepetiFiyatAyarlaCreate.as_view(),
         name="ciceksepeti_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/ciceksepeti-fiyat-guncelle/<int:pk>/', CiceksepetiFiyatAyarlaUpdate.as_view(),
         name="ciceksepeti_fiyat_guncelle"),
    path('xml-yonetimi/fiyat-ayarla/ciceksepeti-fiyat-sil/<int:pk>/', delete_ciceksepeti_karmarji_formset,
         name="ciceksepeti_fiyat_delete"),
    path('xml-yonetimi/fiyat-ayarla/pttavm-fiyat-ayarla/', PttAvmFiyatAyarlaCreate.as_view(),
         name="pttavm_fiyat_ayarla"),
    path('xml-yonetimi/fiyat-ayarla/pttavm-fiyat-guncelle/<int:pk>/', PttAvmFiyatAyarlaUpdate.as_view(),
         name="pttavm_fiyat_guncelle"),
    path('xml-yonetimi/fiyat-ayarla/pttavm-fiyat-sil/<int:pk>/', delete_pttavm_karmarji_formset,
         name="pttavm_fiyat_delete"),

    # trendyol
    path('trendyol/hesap-bilgileri/', trendyol_hesap_bilgileri, name="trendyol_hesap_bilgileri"),
    path('trendyol/urun-giris/', trendyol_urun_girisi, name="trendyol_urun_girisi"),
    path('trendyol/urun-giris/giyim/', trendyol_giyim_urun_girisi, name="trendyol_giyim_urun_girisi"),
    path('trendyol/urun-giris/ayakkabi/', trendyol_ayakkabi_urun_girisi, name="trendyol_ayakkabi_urun_girisi"),
    path('trendyol/urun-giris/ayakkabi-urunleri-getir/<category_no>/', ayakkabi_urunlerini_getir, name="ayakkabi_urunlerini_getir"),
    path('trendyol/urun-giris/gsm-urunleri/', trendyol_gsm_urun_girisi, name="trendyol_gsm_urun_girisi"),
    path('trendyol/urun-giris/aksesuar-urunleri/', trendyol_aksesuar_urun_girisi, name="trendyol_aksesuar_urun_girisi"),
    path('trendyol/ozellik-eslestir/', trendyol_ozellik_eslestir, name="trendyol_ozellik_eslestir"),
    path('trendyol/ozellik-eslestir/ozellik-kaydet/', trendyol_ozellik_kaydet, name="trendyol_ozellik_kaydet"),
    path('trendyol/stok-fiyat-guncelleme/', trendyol_stok_fiyat_guncelle, name="trendyol_stok_fiyat_guncelle"),
    path('trendyol/bilgi-guncelleme/', trendyol_bilgi_guncelle, name="trendyol_bilgi_guncelle"),
    path('trendyol/urun-silme/', trendyol_delete_product, name="trendyol_delete_product"),
    path('trendyol/urunler/', trendyol_yuklu_urunler, name="trendyol_yuklu_urunler"),
    path('trendyol/hatali-urunler/', trendyol_hatali_urunler, name="trendyol_hatali_urunler"),
    path('trendyol/hatali-urunler/aktif-yap/barcode/ajax/', trendyol_hatali_urunler_aktif_yap,
         name="trendyol_hatali_urunler_aktif_yap"),
    path('trendyol/servis-istekleri/', trendyol_batch_request, name="trendyol_batch_request"),
    path('trendyol/servis-istekleri/goruntule/<str:batch_request>/', trendyol_batch_request_detail,
         name="trendyol_batch_request_detail"),
    path('trendyol/servis-istekleri/sil/<int:id>/', trendyol_batch_request_delete,
         name="trendyol_batch_request_delete"),
    path('trendyol/servis-istekleri/tumunu-sil/', trendyol_batch_request_delete_all,
         name="trendyol_batch_request_delete_all"),
    path('trendyol/servis-istekleri/excel-indir/<str:batch_request>/', trendyol_batch_request_export_excell,
         name="trendyol_batch_request_export_excell"),
    path('trendyol/komisyon-oranlari/', trendyol_komisyon, name="trendyol_komisyon"),
    path('trendyol/komisyon-oranlari/komisyon_id=<int:id>/', trendyol_komisyon_detay, name="trendyol_komisyon_detay"),
    path('trendyol/komisyon-oranlari/sil/id=<int:id>/', trendyol_komisyon_sil,
         name='trendyol_komisyon_sil'),
    path('trendyol/indirim-olustur/', trendyol_indirim_olustur, name="trendyol_indirim_olustur"),
    path('trendyol/indirim-olustur/indirim-kaydet/', trendyol_indirim_kaydet, name="trendyol_indirim_kaydet"),

    ## Hepsiburada
    path('hepsiburada/hesap-bilgileri/', hepsiburada_hesap_bilgileri, name="hepsiburada_hesap_bilgileri"),
    path('hepsiburada/urun-giris/', hepsiburada_add_product, name="hepsiburada_add_product"),
    path('hepsiburada/urun-giris/giyim/', hepsiburada_add_product_giyim, name="hepsiburada_add_product_giyim"),
    path('hepsiburada/urun-giris/giyim/kategori_no=<category_no>/', hepsiburada_add_product_giyim_category,
         name="hepsiburada_add_product_giyim_category"),
    path('hepsiburada/urun-giris/giyim/kategori_id=<int:id>/hepsiburada/urun-gonder/',
         hepsiburada_add_product_giyim_send, name="hepsiburada_add_product_giyim_send"),

     ## Çiçeksepeti
    path('ciceksepeti/hesap-bilgileri/', ciceksepeti_hesap_bilgileri, name="ciceksepeti_hesap_bilgileri"),
    path('ciceksepeti/kategori-eslestir/', ciceksepeti_kategori_eslestir, name="ciceksepeti_kategori_eslestir"),
    path('ciceksepeti/kategori-eslestir/kategorileri-al/', kategorileri_al, name="kategorileri_al"),
    path('ciceksepeti/kategori-eslestir/ajax/', ciceksepeti_kategori_eslestir_ajax, name="ciceksepeti_kategori_eslestir_ajax"),
    path('ciceksepeti/urun-girisi/', ciceksepeti_urun_gonder, name="ciceksepeti_urun_gonder"),
    path('ciceksepeti/urun-girisi/urun-gonder/', ciceksepeti_urun_gonder_ajax, name="ciceksepeti_urun_gonder_ajax"),
    path('ciceksepeti/urun-girisi/stok-fiyat-guncelle/', ciceksepeti_stok_fiyat_guncelle, name="ciceksepeti_stok_fiyat_guncelle"),

    # muhasebe
    path('finans-yonetimi/kesilen-faturalar/', kesilen_faturalar, name="kesilen_faturalar"),
    path('finans-yonetimi/kesilen-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_kesilen_fatura,
         name="update_kesilen_fatura"),
    path('finans-yonetimi/kesilen-faturalar/fatura-sil/fatura_id=<int:id>/', delete_kesilen_fatura,
         name="delete_kesilen_fatura"),
    path('finans-yonetimi/kesilen-faturalar/excel/', kesilen_faturalar_export_excel,
         name="kesilen_faturalar_export_excel"),

    path('finans-yonetimi/alinan-faturalar/', alinan_faturalar, name="alinan_faturalar"),
    path('finans-yonetimi/alinan-faturalar/fatura-guncelle/fatura_id=<int:id>/', update_alinan_fatura,
         name="update_alinan_fatura"),
    path('finans-yonetimi/alinan-faturalar/fatura-sil/fatura_id=<int:id>/', delete_alinan_fatura,
         name="delete_alinan_fatura"),
    path('finans-yonetimi/alinan-faturalar/excel/', alinan_faturalar_export_excel,
         name="alinan_faturalar_export_excel"),
    path('harcamalar/', harcamalar, name="harcamalar"),
    path('ajax-urun-alimi/harcama/ekle/', urun_maliyeti_ekle, name="urun_maliyeti_ekle"),
    path('harcamalar/harcama_id=<int:id>/', harcama_detay, name="harcama_detay"),
    path('harcamalar/hepsini-sil/', harcamalar_hepsini_sil,
         name='harcamalar_hepsini_sil'),
    path('harcamalar/export-excel/', harcamalar_export_excel,
         name='harcamalar_export_excel'),
    path('harcamalar/secili-harcama-sil/', harcamalar_secilileri_sil,
         name='harcamalar_secilileri_sil'),
    path('satislar-api/', satislar_api, name="satislar_api"),
    path('kar-api/', kar_api, name="kar_api"),
    path('son-yedi-gun-kar-api/', yedi_gunluk_kar, name="yedi_gunluk_kar"),
    path('en-cok-siparis-gelen-10-sehir/', en_cok_siparis_gelen_10_sehir, name="en_cok_siparis_gelen_10_sehir"),
    path('pazaryerleri-satis-istatistikleri/', pazaryerleri_istatistikler, name="pazaryerleri_istatistikler"),

    path('arama/', ajax_search, name="ajax_search"),
    path('bildirimlerim/', bildirimler, name="bildirimler"),
    path('tum-bildirimleri-okundu-olarak-isaretle/', tum_bildirimleri_okundu_olarak_isaretle,
         name="tum_bildirimleri_okundu_olarak_isaretle"),
    path('tum-bildirimleri-sil/', tum_bildirimleri_sil, name="tum_bildirimleri_sil"),
    path('bildirim-goruntule/bildirim_id=<int:id>/', bildirim_goruntule, name="bildirim_goruntule"),
    path('bildirim-sil/bildirim_id=<int:id>/', bildirim_sil, name="bildirim_sil"),
    path('bildirim-yenile/', refresh_bildirim, name="refresh_bildirim"),

    ##Pazarlama
    path('pazarlama-yonetimi/email-pazarlama/', email_pazarlama, name="email_pazarlama"),

    path('hesap-bilgilerim/', user_info, name='user_info'),
    path('sifre-degistir/', change_password, name='admin_change_password'),
    path('gecmis-kayitlar/guncelleme-gecmisi/', update_history, name='update_history'),
    path('gecmis-kayitlar/guncelleme-gecmisi/tumunu-sil/', update_history_all_delete, name='update_history_all_delete'),
    path('gecmis-kayitlar/guncelleme-gecmisi/sil/id=<int:id>/', update_history_delete, name='update_history_delete'),
]
