# Generated by Django 4.2.2 on 2023-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolFirstCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '4) Trendyol 1. Kategori',
                'verbose_name_plural': '4) Trendyol 1. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolFiveCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '8) Trendyol 5. Kategori',
                'verbose_name_plural': '8) Trendyol 5. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolFourCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '7) Trendyol 4. Kategori',
                'verbose_name_plural': '7) Trendyol 4. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolSecondCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '5) Trendyol 2. Kategori',
                'verbose_name_plural': '5) Trendyol 2. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolSixCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '9) Trendyol 6. Kategori',
                'verbose_name_plural': '9) Trendyol 6. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolThirdCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '6) Trendyol 3. Kategori',
                'verbose_name_plural': '6) Trendyol 3. Kategori',
                'ordering': ['id'],
            },
        ),
    ]
