# Generated by Django 3.2.21 on 2024-03-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('1', 'Ürün Yükleme'), ('2', 'Stok&Fiyat Güncelleme'), ('3', 'Bilgi Güncelleme'), ('4', 'Ürün Silme')], max_length=50, verbose_name='Log Tipi')),
                ('batch_id', models.CharField(max_length=255, null=True, verbose_name='Batch Request ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=255, null=True, verbose_name='Kategori Adı')),
                ('komisyon_tutari', models.FloatField(null=True, verbose_name='Komisyon Tutarı')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Trendyol Komisyon Tutarları',
                'verbose_name_plural': 'Trendyol Komisyon Tutarları',
                'ordering': ['kategori_adi'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolMoreProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, null=True, verbose_name='Sipariş Numarası')),
                ('packet_number', models.CharField(max_length=255, null=True, verbose_name='Paket Numarası')),
                ('quantity', models.BigIntegerField(null=True, verbose_name='Adet')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=100, null=True, verbose_name='Barkod')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beden')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('unit_price', models.FloatField(null=True, verbose_name='Birim Fiyat')),
                ('sales_amount', models.FloatField(null=True, verbose_name='Satış Tutarı')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('İade Edildi', 'İade Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı'), ('Birden Fazla', 'Birden Fazla')], max_length=255, null=True, verbose_name='Durum')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, null=True, verbose_name='Sipariş Numarası')),
                ('packet_number', models.CharField(max_length=255, null=True, verbose_name='Paket Numarası')),
                ('buyer', models.CharField(max_length=255, null=True, verbose_name='Alıcı')),
                ('quantity', models.BigIntegerField(null=True, verbose_name='Adet')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=100, null=True, verbose_name='Barkod')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beden')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('unit_price', models.FloatField(null=True, verbose_name='Birim Fiyat')),
                ('sales_amount', models.FloatField(null=True, verbose_name='Satış Tutarı')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı')),
                ('shippment_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Teslimat Şehri')),
                ('delivery_price', models.FloatField(blank=True, null=True, verbose_name='Kargo Bedeli (KDV Dahil)')),
                ('commission_price', models.FloatField(blank=True, null=True, verbose_name='Komisyon Tutarı')),
                ('service_price', models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli')),
                ('tax_price', models.FloatField(blank=True, null=True, verbose_name='Vergi Tutarı')),
                ('order_date', models.DateTimeField(verbose_name='Sipariş Tarihi')),
                ('is_return', models.BooleanField(default=False, null=True, verbose_name='İade Edildi Mi?')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('İade Edildi', 'İade Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı'), ('Birden Fazla', 'Birden Fazla')], max_length=255, null=True, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Trendyol Siparişler',
                'verbose_name_plural': 'Trendyol Siparişler',
                'ordering': ['-order_date'],
            },
        ),
    ]
