# Generated by Django 3.2.21 on 2024-03-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20240316_1301'),
        ('trendyol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Yayında Mı?')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trendyol Kategori')),
                ('category_id', models.BigIntegerField(blank=True, null=True, verbose_name='Kategori ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Trendyol Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='TrendyolAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendyol_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendyol.trendyolproduct')),
            ],
        ),
    ]
