# Generated by Django 4.2.2 on 2023-09-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0002_trendyolbrand_alter_trendyolfirstcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('1', 'Ürün Yükleme'), ('2', 'Stok&Fiyat Güncelleme'), ('3', 'Bilgi Güncelleme'), ('4', 'Ürün Silme')], max_length=50, verbose_name='Log Tipi')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
