# Generated by Django 3.2.21 on 2024-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0002_trendyolattributes_trendyolproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolattributes',
            name='code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Özellik ID'),
        ),
        migrations.AddField(
            model_name='trendyolattributes',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Özellik Adı'),
        ),
    ]
