# Generated by Django 4.2.2 on 2023-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0003_logrecords'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecords',
            name='batch_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Batch Request ID'),
        ),
    ]
