# Generated by Django 3.2.21 on 2024-03-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20240316_1301'),
        ('trendyol', '0003_auto_20240322_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant', verbose_name='Trendyol Ürün'),
        ),
    ]
