# Generated by Django 3.2.21 on 2024-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0004_alter_trendyolproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolproduct',
            name='is_ready',
            field=models.BooleanField(default=False, null=True, verbose_name='Hazır mı?'),
        ),
    ]
