# Generated by Django 4.2.2 on 2023-09-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0004_logrecords_batch_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logrecords',
            options={'ordering': ['-create_at']},
        ),
    ]
