# Generated by Django 3.2.21 on 2023-10-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0005_alter_logrecords_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, null=True, verbose_name='Sipariş Numarası')),
                ('packet_number', models.CharField(max_length=255, null=True, verbose_name='Paket Numarası')),
                ('buyer', models.CharField(max_length=255, null=True, verbose_name='Alıcı')),
                ('quantity', models.BigIntegerField(null=True, verbose_name='Adet')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=100, null=True, verbose_name='Barkod')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Renk')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beden')),
                ('stock_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stok Kodu')),
                ('unit_price', models.FloatField(null=True, verbose_name='Birim Fiyat')),
                ('sales_amount', models.FloatField(null=True, verbose_name='Satış Tutarı')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='İndirim Tutarı')),
                ('order_date', models.DateTimeField(verbose_name='Sipariş Tarihi')),
            ],
            options={
                'verbose_name': '7) Trendyol Markalar',
                'verbose_name_plural': '7) Trendyol Markalar',
                'ordering': ['-order_number'],
            },
        ),
    ]
