# Generated by Django 3.2.21 on 2024-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0005_trendyolproduct_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolattributes',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Özellik ID'),
        ),
    ]
