# Generated by Django 3.2.21 on 2023-11-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0006_trendyolorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendyolorders',
            options={'ordering': ['-order_number'], 'verbose_name': 'Trendyol Siparişler', 'verbose_name_plural': 'Trendyol Siparişler'},
        ),
        migrations.AddField(
            model_name='trendyolorders',
            name='commission_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Komisyon Tutarı'),
        ),
        migrations.AddField(
            model_name='trendyolorders',
            name='delivery_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Kargo Bedeli (KDV Dahil)'),
        ),
        migrations.AddField(
            model_name='trendyolorders',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('İade Edildi', 'İade Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı')], default='Tamamlandı', max_length=255, null=True, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='trendyolorders',
            name='tax_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Vergi Tutarı'),
        ),
    ]
