# Generated by Django 3.2.21 on 2023-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0007_auto_20231105_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kargo_sirketi', models.CharField(max_length=255, null=True, verbose_name='Kargo Şirketi')),
                ('kargo_tutari', models.FloatField(null=True, verbose_name='Kargo Tutarı (KDV Dahil)')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Trendyol Kargo Ücretleri',
                'verbose_name_plural': 'Trendyol Kargo Ücretleri',
                'ordering': ['kargo_sirketi'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=255, null=True, verbose_name='Kategori Adı')),
                ('komisyon_tutari', models.FloatField(null=True, verbose_name='Komisyon Tutarı')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Trendyol Komisyon Tutarları',
                'verbose_name_plural': 'Trendyol Komisyon Tutarları',
                'ordering': ['kategori_adi'],
            },
        ),
        migrations.AlterModelOptions(
            name='trendyolorders',
            options={'ordering': ['-order_date'], 'verbose_name': 'Trendyol Siparişler', 'verbose_name_plural': 'Trendyol Siparişler'},
        ),
    ]
