# Generated by Django 3.2.21 on 2023-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0008_auto_20231114_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendyolBrand',
        ),
        migrations.DeleteModel(
            name='TrendyolFirstCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolFiveCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolFourCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolSecondCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolSixCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolThirdCategory',
        ),
    ]
