# Generated by Django 3.2.21 on 2023-11-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0009_auto_20231114_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendyolCargo',
        ),
    ]
