# Generated by Django 3.2.21 on 2024-03-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0009_trendyolattributes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolattributes',
            name='customStatus',
            field=models.BooleanField(default=False, null=True, verbose_name='Custom'),
        ),
    ]
