# Generated by Django 3.2.21 on 2024-03-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0010_trendyolattributes_customstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcodes', models.CharField(max_length=5000, null=True, verbose_name='Barkodlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.AlterModelOptions(
            name='trendyolattributes',
            options={'verbose_name': 'Trendyol Ürün Özellikleri', 'verbose_name_plural': 'Trendyol Ürün Özellikleri'},
        ),
        migrations.AlterModelOptions(
            name='trendyolproduct',
            options={'verbose_name': 'Trendyol Ürünler', 'verbose_name_plural': 'Trendyol Ürünler'},
        ),
        migrations.AddField(
            model_name='trendyolattributes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='trendyolattributes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
