# Generated by Django 3.2.21 on 2023-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0010_delete_trendyolcargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolorders',
            name='service_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli'),
        ),
    ]
