# Generated by Django 3.2.21 on 2023-11-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0011_trendyolorders_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolorders',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('İade Edildi', 'İade Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı')], max_length=255, null=True, verbose_name='Durum'),
        ),
    ]
