# Generated by Django 3.2.21 on 2024-03-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20240316_1301'),
        ('trendyol', '0011_auto_20240324_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Rapor Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='TrendyolReportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trendyol.trendyolreport')),
            ],
        ),
        migrations.DeleteModel(
            name='SendProductReport',
        ),
    ]
