# Generated by Django 3.2.21 on 2023-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0012_alter_trendyolorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolorders',
            name='shippment_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teslimat Şehri'),
        ),
    ]
