# Generated by Django 3.2.21 on 2024-03-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0013_alter_trendyolreportproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendyolreport',
            options={'verbose_name': 'Trendyol Rapor', 'verbose_name_plural': 'Trendyol Rapor'},
        ),
        migrations.AlterModelOptions(
            name='trendyolreportproduct',
            options={'verbose_name': 'Trendyol Rapor Ürünler', 'verbose_name_plural': 'Trendyol Rapor Ürünler'},
        ),
    ]
