# Generated by Django 3.2.21 on 2023-11-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0013_trendyolorders_shippment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolorders',
            name='is_return',
            field=models.BooleanField(default=False, null=True, verbose_name='İade Edildi Mi?'),
        ),
    ]
