# Generated by Django 4.2.2 on 2023-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='KDV Hariç Fiyat')),
                ('tax_rate', models.IntegerField(null=True, verbose_name='KVD Oranı')),
                ('file', models.FileField(blank=True, null=True, upload_to='adminpage/kesilen_fatular/', verbose_name='Fatura')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '3) Alınan Faturalar',
                'verbose_name_plural': '3) Alınan Faturalar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Ad/Soyad/Ünvan')),
                ('tax_number', models.BigIntegerField(null=True, verbose_name='Vergi Numarası')),
                ('tax_administration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vergi Dairesi')),
                ('price', models.FloatField(null=True, verbose_name='KDV Hariç Fiyat')),
                ('tax_rate', models.IntegerField(null=True, verbose_name='KVD Oranı')),
                ('file', models.FileField(blank=True, null=True, upload_to='adminpage/kesilen_fatular/', verbose_name='Fatura')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '2) Kesilen Faturalar',
                'verbose_name_plural': '2) Kesilen Faturalar',
                'ordering': ['created_at'],
            },
        ),
    ]
