# Generated by Django 4.2.2 on 2023-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_alter_invoicesreceived_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendyol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Adı')),
                ('kep', models.CharField(blank=True, max_length=255, null=True, verbose_name='KEP Adresi')),
                ('apikey', models.CharField(blank=True, max_length=255, null=True, verbose_name='Api Key')),
                ('apisecret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Api Secret')),
                ('saticiid', models.BigIntegerField(blank=True, null=True, verbose_name='Satıcı ID (Cari ID)')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': '1) Trendyol Hesap Bilgileri',
                'verbose_name_plural': '1) Trendyol Hesap Bilgileri',
            },
        ),
    ]
