# Generated by Django 4.2.2 on 2023-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_trendyol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyol',
            name='iadeadresid_1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 1'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='iadeadresid_2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 2'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='iadeadresid_3',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 3'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='iadeadresid_4',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 4'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='iadeadresid_5',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='İade Adres ID 5'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='sevkiyatadresid_1',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 1'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='sevkiyatadresid_2',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 2'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='sevkiyatadresid_3',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 3'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='sevkiyatadresid_4',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 4'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='sevkiyatadresid_5',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sevkiyat Adres ID 5'),
        ),
    ]
