# Generated by Django 4.2.2 on 2023-09-03 17:57

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0013_delete_trendyolfirstcategory_and_more'),
        ('adminpage', '0008_alter_notification_noti_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Başlık')),
                ('foundation_year', models.CharField(max_length=100, verbose_name='Kuruluş Yılı')),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Misyon')),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Vizyon')),
                ('category_count', models.BigIntegerField(null=True, verbose_name='Kategori Sayısı')),
                ('product_count', models.BigIntegerField(null=True, verbose_name='Ürün Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.maincategory', verbose_name='Kategoriler')),
            ],
        ),
    ]
