# Generated by Django 4.2.2 on 2023-09-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_hakkimizda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizda',
            name='categories',
            field=models.CharField(max_length=500, null=True, verbose_name='Kategoriler'),
        ),
    ]
