# Generated by Django 4.2.2 on 2023-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_alter_hakkimizda_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='company_info',
            field=models.TextField(max_length=5000, null=True, verbose_name='Şirket Hakkında'),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='hepsiburada_url',
            field=models.URLField(null=True, verbose_name='Hepsiburada Mağaza Adresi'),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='pttavm_url',
            field=models.URLField(null=True, verbose_name='PTTAvm Mağaza Adresi'),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='trendyol_url',
            field=models.URLField(null=True, verbose_name='Trendyol Mağaza Adresi'),
        ),
    ]
