# Generated by Django 4.2.2 on 2023-09-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0011_hakkimizda_company_info_hakkimizda_hepsiburada_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyol',
            name='firstbarem',
            field=models.FloatField(null=True, verbose_name='Barem 1. Aralık Maksimum Değeri'),
        ),
        migrations.AddField(
            model_name='trendyol',
            name='secondbarem',
            field=models.FloatField(null=True, verbose_name='Barem 2. Aralık Maksimum Değeri'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='hepsiburada_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Hepsiburada Mağaza Adresi'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='pttavm_url',
            field=models.CharField(max_length=255, null=True, verbose_name='PTTAvm Mağaza Adresi'),
        ),
        migrations.AlterField(
            model_name='hakkimizda',
            name='trendyol_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Trendyol Mağaza Adresi'),
        ),
    ]
