# Generated by Django 4.2.2 on 2023-09-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_trendyol_firstbarem_trendyol_secondbarem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '4) Bildirimler', 'verbose_name_plural': '4) Bildirimler'},
        ),
    ]
