# Generated by Django 3.2.21 on 2023-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0013_alter_notification_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('Belirli Tutar Altı', 'Belirli Tutar Altı'), ('İndirimli Ürünler', 'İndirimli Ürünler')], max_length=100, null=True, verbose_name='Tip')),
                ('banner_title', models.CharField(choices=[('Belirli Tutar Altı', 'Belirli Tutar Altı'), ('İndirimli Ürünler', 'İndirimli Ürünler')], max_length=100, null=True, verbose_name='Banner Başlık')),
                ('banner_minprice', models.IntegerField(blank=True, null=True, verbose_name='En Düşük Fiyat')),
                ('banner_maxprice', models.IntegerField(blank=True, null=True, verbose_name='En Yüksek Fiyat')),
                ('image', models.FileField(blank=True, null=True, upload_to='adminpage/bannerone/', verbose_name='Görsel Seç')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Yayında Mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='BannerTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('Belirli Tutar Altı', 'Belirli Tutar Altı'), ('İndirimli Ürünler', 'İndirimli Ürünler')], max_length=100, null=True, verbose_name='Tip')),
                ('banner_title', models.CharField(choices=[('Belirli Tutar Altı', 'Belirli Tutar Altı'), ('İndirimli Ürünler', 'İndirimli Ürünler')], max_length=100, null=True, verbose_name='Banner Başlık')),
                ('banner_minprice', models.IntegerField(blank=True, null=True, verbose_name='En Düşük Fiyat')),
                ('banner_maxprice', models.IntegerField(blank=True, null=True, verbose_name='En Yüksek Fiyat')),
                ('image', models.FileField(blank=True, null=True, upload_to='adminpage/bannerone/', verbose_name='Görsel Seç')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Yayında Mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
    ]
