# Generated by Django 3.2.21 on 2023-10-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0014_bannerone_bannertwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerone',
            name='banner_discountrate',
            field=models.FloatField(blank=True, null=True, verbose_name='İndirim Oranı'),
        ),
        migrations.AddField(
            model_name='bannertwo',
            name='banner_discountrate',
            field=models.FloatField(blank=True, null=True, verbose_name='İndirim Oranı'),
        ),
    ]
