# Generated by Django 3.2.21 on 2023-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0015_auto_20231001_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerone',
            name='banner_discountrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='İndirim Oranı'),
        ),
        migrations.AlterField(
            model_name='bannertwo',
            name='banner_discountrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='İndirim Oranı'),
        ),
    ]
