# Generated by Django 3.2.21 on 2023-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_auto_20231001_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerone',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bannertwo',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
