# Generated by Django 3.2.21 on 2023-10-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0017_auto_20231001_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerone',
            name='banner_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Banner Başlık'),
        ),
        migrations.AlterField(
            model_name='bannertwo',
            name='banner_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Banner Başlık'),
        ),
    ]
