# Generated by Django 3.2.21 on 2023-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0018_auto_20231001_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerone',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Gideceği URL'),
        ),
        migrations.AddField(
            model_name='bannertwo',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Gideceği URL'),
        ),
    ]
