# Generated by Django 3.2.21 on 2023-10-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0019_auto_20231001_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerone',
            name='link',
        ),
        migrations.RemoveField(
            model_name='bannertwo',
            name='link',
        ),
    ]
