# Generated by Django 3.2.21 on 2023-10-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0020_auto_20231001_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesreceived',
            name='price_amount',
            field=models.FloatField(null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='invoicesreceived',
            name='tax_amount',
            field=models.FloatField(null=True, verbose_name='KDV Tutarı'),
        ),
        migrations.AddField(
            model_name='issuedinvoices',
            name='price_amount',
            field=models.FloatField(null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AddField(
            model_name='issuedinvoices',
            name='tax_amount',
            field=models.FloatField(null=True, verbose_name='KDV Tutarı'),
        ),
    ]
