# Generated by Django 3.2.21 on 2023-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0021_auto_20231012_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesreceived',
            name='bill_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Fatura Numarası'),
        ),
        migrations.AddField(
            model_name='issuedinvoices',
            name='bill_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Fatura Numarası'),
        ),
    ]
