# Generated by Django 3.2.21 on 2023-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0022_auto_20231012_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesreceived',
            name='price_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='invoicesreceived',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='KDV Tutarı'),
        ),
        migrations.AlterField(
            model_name='issuedinvoices',
            name='price_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='issuedinvoices',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='KDV Tutarı'),
        ),
    ]
