# Generated by Django 3.2.21 on 2023-10-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0023_auto_20231012_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicesreceived',
            options={'ordering': ['-created_at'], 'verbose_name': '3) Alınan Faturalar', 'verbose_name_plural': '3) Alınan Faturalar'},
        ),
        migrations.AlterModelOptions(
            name='issuedinvoices',
            options={'ordering': ['-created_at'], 'verbose_name': '2) Kesilen Faturalar', 'verbose_name_plural': '2) Kesilen Faturalar'},
        ),
        migrations.AddField(
            model_name='invoicesreceived',
            name='bill_type',
            field=models.CharField(choices=[('Satış', 'Satış'), ('Genel İade', 'Genel İade'), ('Tevkifat', 'Tevkifat'), ('Tevkifat İade', 'Tevkifat İade'), ('İstisna', 'İstisna'), ('Özel Matrah', 'Özel Matrah'), ('İhraç Kayıtlı', 'İhraç Kayıtlı'), ('Konaklama Vergisi', 'Konaklama Vergisi')], default='Satış', max_length=100, null=True, verbose_name='Fatura Tipi'),
        ),
        migrations.AddField(
            model_name='invoicesreceived',
            name='is_cancelling',
            field=models.BooleanField(default=False, null=True, verbose_name='İptal Edildi Mi?'),
        ),
    ]
