# Generated by Django 3.2.21 on 2023-10-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0024_auto_20231017_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedinvoices',
            name='bill_type',
            field=models.CharField(choices=[('Satış', 'Satış'), ('Genel İade', 'Genel İade'), ('Tevkifat', 'Tevkifat'), ('Tevkifat İade', 'Tevkifat İade'), ('İstisna', 'İstisna'), ('Özel Matrah', 'Özel Matrah'), ('İhraç Kayıtlı', 'İhraç Kayıtlı'), ('Konaklama Vergisi', 'Konaklama Vergisi')], default='Satış', max_length=100, null=True, verbose_name='Fatura Tipi'),
        ),
        migrations.AddField(
            model_name='issuedinvoices',
            name='is_cancelling',
            field=models.BooleanField(default=False, null=True, verbose_name='İptal Edildi Mi?'),
        ),
    ]
