# Generated by Django 3.2.21 on 2023-11-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0025_auto_20231017_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harcamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harcama_tipi', models.CharField(choices=[('Ürün Alımı', 'Ürün Alımı'), ('KDV Ödemesi', 'KDV Ödemesi'), ('Gelir Geçici Vergi Ödemesi', 'Gelir Geçici Vergi Ödemesi'), ('Diğer Harcamalar', 'Diğer Harcamalar')], max_length=100, null=True, verbose_name='Harcama Tipi')),
                ('harcama_adi', models.CharField(max_length=300, null=True, verbose_name='Harcama Adı')),
                ('harcama_tutari', models.FloatField(max_length='Harcama Tutarı', null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Harcama Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Harcamalar',
                'verbose_name_plural': 'Harcamalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='invoicesreceived',
            name='tax_rate',
            field=models.IntegerField(null=True, verbose_name='KDV Oranı'),
        ),
        migrations.AlterField(
            model_name='issuedinvoices',
            name='tax_rate',
            field=models.IntegerField(null=True, verbose_name='KDV Oranı'),
        ),
    ]
