# Generated by Django 3.2.21 on 2023-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0026_auto_20231111_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='harcamalar',
            name='harcama_notu',
            field=models.TextField(null=True, verbose_name='Not'),
        ),
    ]
