# Generated by Django 3.2.21 on 2023-11-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0027_harcamalar_harcama_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harcamalar',
            name='harcama_tutari',
            field=models.FloatField(null=True, verbose_name='Harcama Tutarı'),
        ),
    ]
