# Generated by Django 3.2.21 on 2023-11-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0028_alter_harcamalar_harcama_tutari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harcamalar',
            name='harcama_notu',
            field=models.TextField(blank=True, null=True, verbose_name='Not'),
        ),
    ]
