# Generated by Django 3.2.21 on 2023-11-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0029_alter_harcamalar_harcama_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harcamalar',
            name='created_at',
            field=models.DateField(verbose_name='Harcama Tarihi'),
        ),
    ]
