# Generated by Django 3.2.21 on 2023-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0030_alter_harcamalar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='harcamalar',
            name='durum',
            field=models.CharField(choices=[('Ödeme Yapıldı', 'Ödeme Yapıldı'), ('İptal Edildi', 'İptal Edildi'), ('İade Yapıldı', 'İade Yapıldı')], default='Ödeme Yapıldı', max_length=50, null=True, verbose_name='Ödeme Durumu'),
        ),
    ]
