# Generated by Django 3.2.21 on 2023-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0031_harcamalar_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyol',
            name='hizmet_bedeli',
            field=models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli'),
        ),
    ]
