# Generated by Django 3.2.21 on 2023-11-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0032_trendyol_hizmet_bedeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('Modaymış Güncelleme', 'Modaymış Güncelleme'), ('Modaymış Aktif Olmayan Ürün', 'Modaymış Aktif Olmayan Ürün'), ('Tahtakale Güncelleme', 'Tahtakale Güncelleme'), ('Trendyol Stok&Fiyat Güncelleme', 'Trendyol Stok&Fiyat Güncelleme')], max_length=100, null=True, verbose_name='Geçmiş Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
