# Generated by Django 3.2.21 on 2023-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0034_izinler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harcamalar',
            name='harcama_tipi',
            field=models.CharField(choices=[('Ürün Alımı', 'Ürün Alımı'), ('KDV Ödemesi', 'KDV Ödemesi'), ('Gelir Geçici Vergi Ödemesi', 'Gelir Geçici Vergi Ödemesi'), ('Reklam Harcaması', 'Reklam Harcaması'), ('Diğer Harcamalar', 'Diğer Harcamalar')], max_length=100, null=True, verbose_name='Harcama Tipi'),
        ),
    ]
