# Generated by Django 3.2.21 on 2023-11-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0036_auto_20231122_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hepsiburada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Adı')),
                ('kep', models.CharField(blank=True, max_length=255, null=True, verbose_name='KEP Adresi')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şifre')),
                ('merchantID', models.BigIntegerField(blank=True, null=True, verbose_name='Merchant ID')),
                ('firstbarem', models.FloatField(null=True, verbose_name='Barem 1. Aralık Maksimum Değeri')),
                ('secondbarem', models.FloatField(null=True, verbose_name='Barem 2. Aralık Maksimum Değeri')),
                ('hizmet_bedeli', models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli')),
                ('islem_bedeli', models.FloatField(blank=True, null=True, verbose_name='Hizmet Bedeli')),
            ],
            options={
                'verbose_name': 'Hepsiburada Hesap Bilgileri',
                'verbose_name_plural': 'Hepsiburada Hesap Bilgileri',
            },
        ),
    ]
