# Generated by Django 3.2.21 on 2023-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0038_hepsiburada_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hepsiburada',
            name='islem_bedeli',
            field=models.FloatField(blank=True, null=True, verbose_name='İşlem Bedeli'),
        ),
    ]
