# Generated by Django 3.2.21 on 2023-11-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0039_alter_hepsiburada_islem_bedeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hepsiburada',
            name='merchantID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Merchant ID'),
        ),
    ]
