# Generated by Django 3.2.21 on 2023-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0040_alter_hepsiburada_merchantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='harcamalar',
            name='siparis_numarasi',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Sipariş Numarası'),
        ),
    ]
