# Generated by Django 3.2.21 on 2023-12-10 01:48

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0014_alter_subbottomcategory_options'),
        ('adminpage', '0041_harcamalar_siparis_numarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_type', models.CharField(choices=[('Belirli Tutar Altı', 'Belirli Tutar Altı'), ('İndirimli Ürünler', 'İndirimli Ürünler'), ('Kategori Bazlı Ürünler', 'Kategori Bazlı Ürünler'), ('Kampanya Bazlı Ürünler', 'Kampanya Bazlı Ürünler')], max_length=100, null=True, verbose_name='Tip')),
                ('banner_title', models.CharField(max_length=255, null=True, verbose_name='Banner Başlık')),
                ('banner_maxprice', models.IntegerField(blank=True, null=True, verbose_name='En Yüksek Fiyat')),
                ('banner_discountrate', models.IntegerField(blank=True, null=True, verbose_name='İndirim Oranı')),
                ('banner_campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kampanya Adı')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=50, scale=None, size=[1920, 1080], upload_to='adminpage/banner')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Yayında Mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('viewd_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Görüntülenme Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('banner_category', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.subbottomcategory', verbose_name='Kategori Seçiniz')),
            ],
        ),
        migrations.DeleteModel(
            name='BannerOne',
        ),
        migrations.DeleteModel(
            name='BannerTwo',
        ),
    ]
