# Generated by Django 3.2.21 on 2023-12-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0042_auto_20231210_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_campaign',
        ),
    ]
