# Generated by Django 3.2.21 on 2023-12-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0043_remove_banner_banner_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(null=True, verbose_name='Sıra Sayısı'),
        ),
    ]
