# Generated by Django 3.2.21 on 2023-12-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_productmodelgroup'),
        ('adminpage', '0044_banner_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Kampanya Adı')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Açıklama')),
                ('discountrate', models.PositiveIntegerField(default=0, verbose_name='İndirim Oranı')),
                ('image', models.FileField(blank=True, null=True, upload_to='adminpage/campaign', verbose_name='Kampanya Resmi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='CampaingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaing_products', to='adminpage.campaign')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct', verbose_name='Kampanya Ürünü')),
            ],
        ),
    ]
