# Generated by Django 3.2.21 on 2023-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0045_auto_20231210_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='Yayında mı?'),
        ),
    ]
