# Generated by Django 3.2.21 on 2023-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0046_campaign_is_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tredyshop_liste_duzeltme', models.FloatField(blank=True, null=True, verbose_name='TredyShop Düzeltme Fiyatı')),
                ('trendyol_liste_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Trendyol Liste Fiyatı Düzeltme')),
                ('trendyol_satis_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Trendyol Satış Fiyatı Düzeltme')),
                ('hepsiburada_liste_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Hepsiburada Liste Fiyatı Düzeltme')),
                ('hepsiburada_satis_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Hepsiburada Satış Fiyatı Düzeltme')),
                ('amazon_liste_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Amazon Liste Fiyatı Düzeltme')),
                ('amazon_satis_duzeltme', models.FloatField(blank=True, null=True, verbose_name='Amazon Satış Fiyatı')),
                ('pttavm_liste_duzeltme', models.FloatField(blank=True, null=True, verbose_name='PTT Avm Liste Düzeltme Fiyatı')),
                ('pttavm_satis_duzeltme', models.FloatField(blank=True, null=True, verbose_name='PTT Avm Satış Fiyatı Düzeltme')),
            ],
        ),
    ]
