# Generated by Django 3.2.21 on 2023-12-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0047_fiyatayarla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiyatAyarla',
        ),
    ]
