# Generated by Django 3.2.21 on 2023-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0048_delete_fiyatayarla'),
    ]

    operations = [
        migrations.CreateModel(
            name='TredyShopFiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv', models.FloatField(null=True, verbose_name='Genel KDV Oranı')),
                ('commission', models.FloatField(null=True, verbose_name='Sanal POS Komisyon Oranı')),
                ('kargo', models.FloatField(null=True, verbose_name='Kargo Maliyeti')),
                ('satis_fiyati', models.FloatField(null=True, verbose_name='Satış Fiyatı Düzeltme')),
                ('tahmini_kar', models.FloatField(blank=True, null=True, verbose_name='Tahmini Kar')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
    ]
