# Generated by Django 3.2.21 on 2023-12-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0049_tredyshopfiyatayarla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tredyshopfiyatayarla',
            name='tahmini_kar',
        ),
    ]
