# Generated by Django 3.2.21 on 2023-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0050_remove_tredyshopfiyatayarla_tahmini_kar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tredyshopfiyatayarla',
            name='satis_fiyati',
        ),
        migrations.AddField(
            model_name='tredyshopfiyatayarla',
            name='kar_marji',
            field=models.FloatField(null=True, verbose_name='Beklenen Kar Marjı'),
        ),
    ]
