# Generated by Django 3.2.21 on 2023-12-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0051_auto_20231215_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonFiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv1', models.FloatField(null=True, verbose_name='KDV Oranı 1')),
                ('kdv2', models.FloatField(null=True, verbose_name='KDV Oranı 2')),
                ('commission', models.FloatField(null=True, verbose_name='Trendyol Komisyonu')),
                ('service', models.FloatField(null=True, verbose_name='Hizmet Bedeli')),
                ('kargo', models.FloatField(null=True, verbose_name='Kargo Maliyeti')),
                ('indirim', models.FloatField(null=True, verbose_name='İndirim Tutarı')),
                ('kar_marji', models.FloatField(null=True, verbose_name='Beklenen Kar Marjı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='HepsiburadaFiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv1', models.FloatField(null=True, verbose_name='KDV Oranı 1')),
                ('kdv2', models.FloatField(null=True, verbose_name='KDV Oranı 2')),
                ('commission', models.FloatField(null=True, verbose_name='Trendyol Komisyonu')),
                ('service', models.FloatField(null=True, verbose_name='Hizmet Bedeli')),
                ('kargo', models.FloatField(null=True, verbose_name='Kargo Maliyeti')),
                ('indirim', models.FloatField(null=True, verbose_name='İndirim Tutarı')),
                ('kar_marji', models.FloatField(null=True, verbose_name='Beklenen Kar Marjı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='PttAvmFiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv1', models.FloatField(null=True, verbose_name='KDV Oranı 1')),
                ('kdv2', models.FloatField(null=True, verbose_name='KDV Oranı 2')),
                ('commission', models.FloatField(null=True, verbose_name='Trendyol Komisyonu')),
                ('service', models.FloatField(null=True, verbose_name='Hizmet Bedeli')),
                ('kargo', models.FloatField(null=True, verbose_name='Kargo Maliyeti')),
                ('indirim', models.FloatField(null=True, verbose_name='İndirim Tutarı')),
                ('kar_marji', models.FloatField(null=True, verbose_name='Beklenen Kar Marjı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='TrendyolFiyatAyarla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv1', models.FloatField(null=True, verbose_name='KDV Oranı 1')),
                ('kdv2', models.FloatField(null=True, verbose_name='KDV Oranı 2')),
                ('commission', models.FloatField(null=True, verbose_name='Trendyol Komisyonu')),
                ('service', models.FloatField(null=True, verbose_name='Hizmet Bedeli')),
                ('kargo', models.FloatField(null=True, verbose_name='Kargo Maliyeti')),
                ('indirim', models.FloatField(null=True, verbose_name='İndirim Tutarı')),
                ('kar_marji', models.FloatField(null=True, verbose_name='Beklenen Kar Marjı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
        ),
        migrations.RemoveField(
            model_name='tredyshopfiyatayarla',
            name='kdv',
        ),
        migrations.AddField(
            model_name='tredyshopfiyatayarla',
            name='kdv1',
            field=models.FloatField(null=True, verbose_name='KDV Oranı 1'),
        ),
        migrations.AddField(
            model_name='tredyshopfiyatayarla',
            name='kdv2',
            field=models.FloatField(null=True, verbose_name='KDV Oranı 2'),
        ),
    ]
