# Generated by Django 3.2.21 on 2023-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0052_auto_20231215_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonfiyatayarla',
            name='commission',
            field=models.FloatField(null=True, verbose_name='Hepsiburada Komisyonu'),
        ),
        migrations.AlterField(
            model_name='hepsiburadafiyatayarla',
            name='commission',
            field=models.FloatField(null=True, verbose_name='Hepsiburada Komisyonu'),
        ),
        migrations.AlterField(
            model_name='pttavmfiyatayarla',
            name='commission',
            field=models.FloatField(null=True, verbose_name='Hepsiburada Komisyonu'),
        ),
    ]
