# Generated by Django 3.2.21 on 2023-12-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0055_auto_20231215_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='TredyShopKarMarji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.FloatField(null=True, verbose_name='Başlangıç Fiyatı')),
                ('bitis', models.FloatField(null=True, verbose_name='Bitiş Fiyatı')),
                ('kar_maji', models.FloatField(null=True, verbose_name='Kar Marjı')),
                ('tredyshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.tredyshopfiyatayarla')),
            ],
        ),
        migrations.DeleteModel(
            name='KarMarji',
        ),
    ]
