# Generated by Django 3.2.21 on 2023-12-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0056_auto_20231215_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tredyshopfiyatayarla',
            name='kar_marji',
        ),
    ]
