# Generated by Django 3.2.21 on 2023-12-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0057_remove_tredyshopfiyatayarla_kar_marji'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolKarMarji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.FloatField(null=True, verbose_name='Başlangıç Fiyatı')),
                ('bitis', models.FloatField(null=True, verbose_name='Bitiş Fiyatı')),
                ('kar_maji', models.FloatField(null=True, verbose_name='Kar Marjı')),
                ('trendyol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.trendyolfiyatayarla')),
            ],
        ),
        migrations.CreateModel(
            name='PttAvmKarMarji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.FloatField(null=True, verbose_name='Başlangıç Fiyatı')),
                ('bitis', models.FloatField(null=True, verbose_name='Bitiş Fiyatı')),
                ('kar_maji', models.FloatField(null=True, verbose_name='Kar Marjı')),
                ('pttavm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.pttavmfiyatayarla')),
            ],
        ),
        migrations.CreateModel(
            name='HepsiburadaKarMarji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.FloatField(null=True, verbose_name='Başlangıç Fiyatı')),
                ('bitis', models.FloatField(null=True, verbose_name='Bitiş Fiyatı')),
                ('kar_maji', models.FloatField(null=True, verbose_name='Kar Marjı')),
                ('hepsiburada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.hepsiburadafiyatayarla')),
            ],
        ),
        migrations.CreateModel(
            name='AmazonKarMarji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.FloatField(null=True, verbose_name='Başlangıç Fiyatı')),
                ('bitis', models.FloatField(null=True, verbose_name='Bitiş Fiyatı')),
                ('kar_maji', models.FloatField(null=True, verbose_name='Kar Marjı')),
                ('amazon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.amazonfiyatayarla')),
            ],
        ),
    ]
