# Generated by Django 3.2.21 on 2023-12-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0058_amazonkarmarji_hepsiburadakarmarji_pttavmkarmarji_trendyolkarmarji'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonkarmarji',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='amazonkarmarji',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='hepsiburadakarmarji',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='hepsiburadakarmarji',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='pttavmkarmarji',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='pttavmkarmarji',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='tredyshopkarmarji',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='tredyshopkarmarji',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='trendyolkarmarji',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='trendyolkarmarji',
            name='update_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
