# Generated by Django 3.2.21 on 2023-12-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0059_auto_20231215_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSellStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=255, null=True, unique=True, verbose_name='Ürün Barkodu')),
                ('image_url', models.CharField(max_length=500, null=True, verbose_name='Ürün Linki')),
                ('order_number', models.CharField(max_length=150, null=True, verbose_name='Sipariş Numarası')),
                ('sell_count', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Toplam Satış Sayısı')),
                ('satis', models.FloatField(default=0.0, verbose_name='Satış Fiyatı')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('maliyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.harcamalar', verbose_name='Harcama')),
            ],
        ),
    ]
