# Generated by Django 3.2.21 on 2023-12-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0060_productsellstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellstatistic',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ürün Linki'),
        ),
        migrations.AlterField(
            model_name='productsellstatistic',
            name='satis',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Satış Fiyatı'),
        ),
    ]
