# Generated by Django 3.2.21 on 2023-12-17 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0061_auto_20231217_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellstatistic',
            name='maliyet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.harcamalar', verbose_name='Harcama'),
        ),
    ]
