# Generated by Django 3.2.21 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0063_alter_productsellstatistic_maliyet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsellstatistic',
            name='barcode',
        ),
        migrations.AddField(
            model_name='productsellstatistic',
            name='model_code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Model Kodu'),
        ),
    ]
