# Generated by Django 3.2.21 on 2023-12-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0064_auto_20231217_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsellstatistic',
            name='model_code',
        ),
        migrations.AddField(
            model_name='productsellstatistic',
            name='barcode',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ürün Barkodu'),
        ),
    ]
