# Generated by Django 3.2.21 on 2023-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0065_auto_20231217_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellstatistic',
            name='maliyet',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Maliyet Fiyatı'),
        ),
    ]
