# Generated by Django 3.2.21 on 2023-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0066_alter_productsellstatistic_maliyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellstatistic',
            name='maliyet',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Maliyet Fiyatı'),
        ),
    ]
