# Generated by Django 3.2.21 on 2023-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0067_alter_productsellstatistic_maliyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedinvoices',
            name='tax_number',
            field=models.BigIntegerField(default='11111111111', null=True, verbose_name='Vergi Numarası'),
        ),
    ]
