# Generated by Django 3.2.21 on 2023-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0069_alter_issuedinvoices_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedinvoices',
            name='tax_number',
            field=models.BigIntegerField(null=True, verbose_name='Vergi Numarası'),
        ),
    ]
