# Generated by Django 3.2.21 on 2023-12-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0071_campaingproduct_model_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaingproduct',
            name='model_code',
        ),
    ]
