# Generated by Django 3.2.21 on 2023-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0072_remove_campaingproduct_model_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('free_shipping', models.BigIntegerField(blank=True, null=True, verbose_name='Ücretsiz Kargo Tutarı')),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması')),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kargo Ücreti')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anahtar Kelime')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket Adı')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Şirket Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('vkn', models.CharField(blank=True, max_length=50, verbose_name='Vergi Kimlik Numarası')),
                ('mersis', models.CharField(blank=True, max_length=100, verbose_name='Mersis Numarası')),
                ('logo', models.ImageField(blank=True, upload_to='img/logo/')),
                ('icon', models.ImageField(blank=True, upload_to='img/favicon/')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='İnstagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('aboutus', models.TextField(blank=True, null=True, verbose_name='Hakkımızda')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referanslar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
