# Generated by Django 3.2.21 on 2023-12-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0073_sitesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='aboutus',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='references',
        ),
    ]
