# Generated by Django 3.2.21 on 2023-12-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0074_auto_20231221_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='icon',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='img/favicon/', verbose_name='Site Faviconu'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/logo/', verbose_name='Site Logosu'),
        ),
    ]
