# Generated by Django 3.2.21 on 2023-12-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0075_auto_20231221_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='is_active',
        ),
    ]
