# Generated by Django 3.2.21 on 2023-12-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0076_remove_sitesetting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Google Analytics Kodu'),
        ),
    ]
