# Generated by Django 3.2.21 on 2023-12-21 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_rename_modal_code_productmodelgroup_model_code'),
        ('adminpage', '0077_sitesetting_google_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct', verbose_name='Ürün'),
        ),
    ]
