# Generated by Django 3.2.21 on 2023-12-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_rename_modal_code_productmodelgroup_model_code'),
        ('adminpage', '0078_notification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.question', verbose_name='Soru'),
        ),
    ]
