# Generated by Django 3.2.21 on 2023-12-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0019_alter_trendyolorders_status'),
        ('orders', '0047_order_order_platform'),
        ('adminpage', '0079_auto_20231221_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsellstatistic',
            name='order_number',
        ),
        migrations.AddField(
            model_name='notification',
            name='tredyshop_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Tredyshop Siparişi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='trendyol_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trendyol.trendyolorders', verbose_name='Trendyol Siparişi'),
        ),
    ]
