# Generated by Django 3.2.21 on 2023-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0080_auto_20231223_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='history_type',
            field=models.CharField(choices=[('Modaymış Yeni Ürün Ekleme', 'Modaymış Yeni Ürün Ekleme'), ('Modaymış Güncelleme', 'Modaymış Güncelleme'), ('Modaymış Aktif Olmayan Ürün', 'Modaymış Aktif Olmayan Ürün'), ('Tahtakale Güncelleme', 'Tahtakale Güncelleme'), ('Trendyol Stok&Fiyat Güncelleme', 'Trendyol Stok&Fiyat Güncelleme'), ('XML Dünyası Yeni Ürün Ekleme', 'XML Dünyası Yeni Ürün Ekleme'), ('XML Dünyası Güncelleme', 'XML Dünyası Güncelleme'), ('XML Dünyası Aktif Olmayan Ürün', 'XML Dünyası Aktif Olmayan Ürün')], max_length=100, null=True, verbose_name='Geçmiş Tipi'),
        ),
    ]
