# Generated by Django 3.2.21 on 2024-01-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0081_alter_updatehistory_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='history_type',
            field=models.CharField(choices=[('Modaymış Yeni Ürün Ekleme', 'Modaymış Yeni Ürün Ekleme'), ('Modaymış Güncelleme', 'Modaymış Güncelleme'), ('Modaymış Aktif Olmayan Ürün', 'Modaymış Aktif Olmayan Ürün'), ('Tahtakale Güncelleme', 'Tahtakale Güncelleme'), ('Trendyol Stok&Fiyat Güncelleme', 'Trendyol Stok&Fiyat Güncelleme'), ('XML Dünyası Yeni Ürün Ekleme', 'XML Dünyası Yeni Ürün Ekleme'), ('XML Dünyası Güncelleme', 'XML Dünyası Güncelleme'), ('XML Dünyası Aktif Olmayan Ürün', 'XML Dünyası Aktif Olmayan Ürün'), ('XML Dünyası Diğer Ürün Ekleme', 'XML Dünyası Diğer Ürün Ekleme'), ('XML Dünyası Ürün Diğer', 'XML Dünyası Ürün Diğer')], max_length=100, null=True, verbose_name='Geçmiş Tipi'),
        ),
    ]
