# Generated by Django 3.2.21 on 2024-01-22 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpage', '0082_alter_updatehistory_history_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Görev Adı')),
                ('task_time', models.CharField(blank=True, choices=[('Her Gün', 'Her Gün'), ('Belirli Gün', 'Belirli Gün')], max_length=500, null=True, verbose_name='Görev Zamanı')),
                ('task_date', models.DateField(blank=True, null=True, verbose_name='Görev Zamanı')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı Mı')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_completed', models.BooleanField(default=False, verbose_name='Hepsi Tamamladı Mı?')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.task', verbose_name='Görev')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
