# Generated by Django 3.2.21 on 2024-01-22 16:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0083_task_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
