# Generated by Django 3.2.21 on 2024-01-22 18:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0084_task_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Görev Açıklaması'),
        ),
    ]
