# Generated by Django 3.2.21 on 2024-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0085_auto_20240122_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Task ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='noti_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=20, verbose_name='Bildirim Tipi'),
        ),
    ]
