# Generated by Django 3.2.21 on 2024-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0086_auto_20240122_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_time',
            field=models.CharField(blank=True, choices=[('Her Gün', 'Her Gün'), ('Belirli Gün', 'Belirli Gün'), ('Son Gün', 'Son Gün')], max_length=500, null=True, verbose_name='Görev Zamanı'),
        ),
    ]
