# Generated by Django 3.2.21 on 2024-01-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hepsiburada', '0004_rename_trendyolmoreproductorder_hepsiburadamoreproductorder'),
        ('adminpage', '0089_alter_notification_noti_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hepsiburada_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hepsiburada.hepsiburadasiparisler', verbose_name='Trendyol Siparişi'),
        ),
    ]
