# Generated by Django 3.2.21 on 2024-02-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0090_notification_hepsiburada_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonFiyatAyarla',
            new_name='CiceksepetiFiyatAyarla',
        ),
        migrations.RenameModel(
            old_name='AmazonKarMarji',
            new_name='CiceksepetiKarMarji',
        ),
    ]
