# Generated by Django 3.2.21 on 2024-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0091_auto_20240214_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciceksepetifiyatayarla',
            name='commission',
            field=models.FloatField(null=True, verbose_name='Çiçeksepeti Komisyonu'),
        ),
    ]
