# Generated by Django 3.2.21 on 2024-02-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0092_alter_ciceksepetifiyatayarla_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciceksepetikarmarji',
            old_name='amazon',
            new_name='ciceksepeti',
        ),
    ]
