# Generated by Django 3.2.21 on 2024-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0093_rename_amazon_ciceksepetikarmarji_ciceksepeti'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontentHeaderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='Başlık')),
                ('url', models.URLField(null=True, verbose_name='Gideceği URL')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
