# Generated by Django 3.2.21 on 2024-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0094_frontentheadercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontentheadercategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sırası'),
        ),
    ]
