# Generated by Django 3.2.21 on 2024-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0095_frontentheadercategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontentheadercategory',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Yayın Durumu'),
        ),
    ]
