# Generated by Django 3.2.21 on 2024-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0097_rename_status_frontentheadercategory_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Gideceği URL'),
        ),
    ]
