# Generated by Django 3.2.21 on 2024-02-28 16:19

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0098_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='ciceksepeti_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Çiçeksepeti Mağaza Adresi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='adminpage/banner'),
        ),
    ]
