# Generated by Django 3.2.21 on 2024-03-02 16:45

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Şehir Adı')),
                ('code', models.IntegerField(null=True, verbose_name='Plaka Kodu')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Şehirler',
                'verbose_name_plural': '2) Şehirler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Teslimat Koşulları')),
                ('membership', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Üyelik Sözleşmesi')),
                ('term_of_use', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Site Kullanım Şartları')),
                ('security', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Gizlilik Politikası')),
                ('kvkk', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='KVKK Aydınlatma Politası')),
                ('cookie', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Cookies')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '7) Sözleşmeler',
                'verbose_name_plural': '7) Sözleşmeler',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Sağlayıcısı')),
                ('cookie_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie İsmi')),
                ('cookie_aim', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Amacı')),
                ('cookie_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Tipi')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '8) Çerezler',
                'verbose_name_plural': '8) Çerezler',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MostSearchingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('count', models.BigIntegerField(default=0, null=True, verbose_name='Arama Sayısı')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '5) En Çok Aranan Kelimeler',
                'verbose_name_plural': '5) En Çok Aranan Kelimeler',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('free_shipping', models.BigIntegerField(blank=True, null=True, verbose_name='Ücretsiz Kargo Tutarı')),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması')),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kargo Ücreti')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anahtar Kelime')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket Adı')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Şirket Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('vkn', models.CharField(blank=True, max_length=50, verbose_name='Vergi Kimlik Numarası')),
                ('mersis', models.CharField(blank=True, max_length=100, verbose_name='Mersis Numarası')),
                ('logo', models.ImageField(blank=True, upload_to='img/logo/')),
                ('icon', models.ImageField(blank=True, upload_to='img/favicon/')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='İnstagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('aboutus', models.TextField(blank=True, null=True, verbose_name='Hakkımızda')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referanslar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1) Ayarlar',
                'verbose_name_plural': '1) Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Soru')),
                ('answer', models.TextField(max_length=1000, null=True, verbose_name='Cevap')),
                ('icon', models.CharField(blank=True, max_length=5000, null=True, verbose_name='İkon')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '6) Sıkça Sorulan Sorular',
                'verbose_name_plural': '6) Sıkça Sorulan Sorular',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='İlçe Adı')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.city', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': '3) İlçeler',
                'verbose_name_plural': '3) İlçeler',
                'ordering': ['id'],
            },
        ),
    ]
