# Generated by Django 4.2.2 on 2023-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anahtar Kelime')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şirket Adı')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Şirket Adresi')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('smtpserver', models.CharField(max_length=50, verbose_name='Smtp Server')),
                ('smtpemail', models.CharField(max_length=50, verbose_name='Smtp Email')),
                ('smtppassword', models.CharField(max_length=50, verbose_name='Smtp Şifre')),
                ('smtpport', models.CharField(blank=True, max_length=10, verbose_name='Smtp Port')),
                ('icon', models.ImageField(blank=True, upload_to='img/favicon/')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='İnstagram')),
                ('twitter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter')),
                ('youtube', models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiktok')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp')),
                ('aboutus', models.TextField(blank=True, null=True, verbose_name='Hakkımızda')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referanslar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
