# Generated by Django 4.2.2 on 2023-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookies',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Aktif mi?'),
        ),
    ]
