# Generated by Django 4.2.2 on 2023-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Ayarlar', 'verbose_name_plural': 'Ayarlar'},
        ),
        migrations.AddField(
            model_name='setting',
            name='free_shipping',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Ücretsiz Kargo Tutarı'),
        ),
    ]
