# Generated by Django 4.2.2 on 2023-06-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_setting_options_setting_free_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Şehir Adı')),
                ('code', models.IntegerField(null=True, verbose_name='Plaka Kodu')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2) Şehirler',
                'verbose_name_plural': '2) Şehirler',
            },
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': '1) Ayarlar', 'verbose_name_plural': '1) Ayarlar'},
        ),
    ]
