# Generated by Django 4.2.2 on 2023-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_cookies_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title_color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık Rengi'),
        ),
    ]
