# Generated by Django 4.2.2 on 2023-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_slider_title_alter_slider_title_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Button Yazısı'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Buton Rengi'),
        ),
    ]
