# Generated by Django 4.2.2 on 2023-06-19 18:19

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['code'], 'verbose_name': '2) Şehirler', 'verbose_name_plural': '2) Şehirler'},
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='İlçe Adı')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.city', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': '3) İlçeler',
                'verbose_name_plural': '3) İlçeler',
                'ordering': ['id'],
            },
        ),
    ]
