# Generated by Django 4.2.2 on 2023-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_slider_button_alter_slider_button_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=40, null=True, verbose_name='Başlık'),
        ),
    ]
