# Generated by Django 4.2.2 on 2023-06-22 20:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_city_options_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True, verbose_name='Başlık')),
                ('title_color', models.CharField(max_length=40, null=True, verbose_name='Başlık Rengi')),
                ('subtitle', models.CharField(max_length=40, null=True, verbose_name='Alt Başlık')),
                ('subtitle_color', models.CharField(max_length=40, null=True, verbose_name='Alt Başlık Rengi')),
                ('button', models.CharField(max_length=40, null=True, verbose_name='Button Yazısı')),
                ('button_color', models.CharField(max_length=40, null=True, verbose_name='Buton Rengi')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '4) Slider',
                'verbose_name_plural': '4) Slider',
                'ordering': ['id'],
            },
        ),
    ]
