# Generated by Django 4.2.2 on 2023-07-22 18:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_slider_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='cookie',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Cookies'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='delivery',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Teslimat Koşulları'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='kvkk',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='KVKK Aydınlatma Politası'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='membership',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Üyelik Sözleşmesi'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='security',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Gizlilik Politikası'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='term_of_use',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Site Kullanım Şartları'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='İçerik'),
        ),
    ]
