# Generated by Django 4.2.2 on 2023-06-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_publish',
            field=models.BooleanField(default=True, null=True, verbose_name='Yayınlansın'),
        ),
    ]
