# Generated by Django 4.2.2 on 2023-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_slider_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
