# Generated by Django 4.2.2 on 2023-07-22 19:58

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_contracts_cookie_alter_contracts_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='cookie',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Cookies'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='delivery',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Teslimat Koşulları'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='kvkk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='KVKK Aydınlatma Politası'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='membership',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Üyelik Sözleşmesi'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='security',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Gizlilik Politikası'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='term_of_use',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Site Kullanım Şartları'),
        ),
    ]
