# Generated by Django 4.2.2 on 2023-06-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_slider_created_at_alter_slider_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='img/slider/'),
        ),
    ]
