# Generated by Django 4.2.2 on 2023-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_contracts_cookie_alter_contracts_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mersis',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mersis Numarası'),
        ),
        migrations.AddField(
            model_name='setting',
            name='vkn',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vergi Kimlik Numarası'),
        ),
    ]
