# Generated by Django 3.2.21 on 2023-10-01 09:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_setting_mersis_setting_vkn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='İçerik'),
        ),
    ]
