# Generated by Django 3.2.21 on 2023-10-01 09:35

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_slider_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='İçerik'),
        ),
    ]
