# Generated by Django 4.2.2 on 2023-06-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='is_publish',
            field=models.BooleanField(default=True, help_text='1071px x 593px', null=True, verbose_name='Yayınlansın'),
        ),
    ]
