# Generated by Django 4.2.2 on 2023-06-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_slider_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(help_text='1071px x 593px', null=True, upload_to='img/slider/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_publish',
            field=models.BooleanField(default=True, null=True, verbose_name='Yayınlansın'),
        ),
    ]
