# Generated by Django 3.2.21 on 2023-12-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_alter_slider_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sss',
            options={'ordering': ['-id'], 'verbose_name': '6) Sıkça Sorulan Sorular', 'verbose_name_plural': '6) Sıkça Sorulan Sorular'},
        ),
    ]
