# Generated by Django 4.2.2 on 2023-06-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_slider_image_alter_slider_is_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle_color',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Alt Başlık Rengi'),
        ),
    ]
