# Generated by Django 3.2.21 on 2023-12-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_alter_sss_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
