# Generated by Django 4.2.2 on 2023-06-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_alter_slider_subtitle_alter_slider_subtitle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Gideceği Adres'),
        ),
    ]
