# Generated by Django 4.2.2 on 2023-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_slider_button_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostSearchingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '5) En Çok Aranan Kelimeler',
                'verbose_name_plural': '5) En Çok Aranan Kelimeler',
                'ordering': ['created_at'],
            },
        ),
    ]
