# Generated by Django 4.2.2 on 2023-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_mostsearchingkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostsearchingkeyword',
            name='count',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Arama Sayısı'),
        ),
    ]
