# Generated by Django 4.2.2 on 2023-06-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_mostsearchingkeyword_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostsearchingkeyword',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
