# Generated by Django 4.2.2 on 2023-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_mostsearchingkeyword_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='shipping_company',
            field=models.CharField(max_length=100, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='setting',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Kargo Ücreti'),
        ),
    ]
