# Generated by Django 4.2.2 on 2023-06-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_setting_shipping_company_setting_shipping_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Firması'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='shipping_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kargo Ücreti'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtpemail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Smtp Email'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtppassword',
            field=models.CharField(blank=True, max_length=50, verbose_name='Smtp Şifre'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smtpserver',
            field=models.CharField(blank=True, max_length=50, verbose_name='Smtp Server'),
        ),
    ]
