# Generated by Django 4.2.2 on 2023-07-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0019_alter_setting_shipping_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='type',
            field=models.CharField(choices=[('Ürün', 'Ürün'), ('Bilgi', 'Bilgi'), ('Duyuru', 'Duyuru')], default='Bilgi', max_length=30, null=True, verbose_name='Slider Tipi'),
        ),
    ]
