# Generated by Django 4.2.2 on 2023-07-11 20:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0020_slider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
