# Generated by Django 4.2.2 on 2023-07-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0021_slider_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Soru')),
                ('answer', models.TextField(max_length=1000, null=True, verbose_name='Cevap')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '6) Sıkça Sorulan Sorular',
                'verbose_name_plural': '6) Sıkça Sorulan Sorular',
                'ordering': ['created_at'],
            },
        ),
    ]
