# Generated by Django 4.2.2 on 2023-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0022_sss'),
    ]

    operations = [
        migrations.AddField(
            model_name='sss',
            name='icon',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='İkon'),
        ),
    ]
