# Generated by Django 4.2.2 on 2023-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0023_sss_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sss',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='İkon'),
        ),
    ]
