# Generated by Django 4.2.2 on 2023-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0024_alter_sss_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sss',
            name='icon',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='İkon'),
        ),
    ]
