# Generated by Django 4.2.2 on 2023-07-17 20:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0025_alter_sss_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Teslimat Koşulları')),
                ('membership', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Üyelik Sözleşmesi')),
                ('term_of_use', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Site Kullanım Şartları')),
                ('security', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Gizlilik Politikası')),
                ('kvkk', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='KVKK Aydınlatma Politası')),
                ('cookie', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Cookies')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '7) Sözleşmeler',
                'verbose_name_plural': '7) Sözleşmeler',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Sağlayıcısı')),
                ('cookie_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie İsmi')),
                ('cookie_aim', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Amacı')),
                ('cookie_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cookie Tipi')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '8) Çerezler',
                'verbose_name_plural': '8) Çerezler',
                'ordering': ['created_at'],
            },
        ),
    ]
