# Generated by Django 3.2.21 on 2024-03-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('order', models.IntegerField(null=True, verbose_name='Sırası')),
                ('category_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '1) 1. Düzey Kategori',
                'verbose_name_plural': '1) 1. Düzey Kategori',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('category_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categorymodel.maincategory', verbose_name='Ana Kategori')),
            ],
            options={
                'verbose_name': '2) 2. Düzey Kategori',
                'verbose_name_plural': '2) 2. Düzey Kategori',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubBottomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('keyword', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/category/')),
                ('category_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayınlansın mı?')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategories', to='categorymodel.maincategory', verbose_name='Ana Kategori')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbottomcategories', to='categorymodel.subcategory', verbose_name='Alt Kategori')),
            ],
            options={
                'verbose_name': '3) 3. Düzey Kategori',
                'verbose_name_plural': '3) 3. Düzey Kategori',
                'ordering': ('title',),
            },
        ),
    ]
