# Generated by Django 4.2.2 on 2023-07-24 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0002_alter_maincategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbottomcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbottomcategories', to='categorymodel.subcategory', verbose_name='Alt Kategori'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categorymodel.maincategory', verbose_name='Ana Kategori'),
        ),
    ]
