# Generated by Django 4.2.2 on 2023-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0002_alter_maincategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AlterField(
            model_name='subbottomcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Yayınlansın mı?'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Yayınlansın mı?'),
        ),
    ]
