# Generated by Django 4.2.2 on 2023-08-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0003_alter_subbottomcategory_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='category_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası'),
        ),
    ]
