# Generated by Django 4.2.2 on 2023-08-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0004_maincategory_category_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası'),
        ),
    ]
