# Generated by Django 4.2.2 on 2023-06-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0005_alter_subcategory_maincategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='maincategory',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categorymodel.maincategory'),
        ),
        migrations.DeleteModel(
            name='SubBottomCategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
