# Generated by Django 4.2.2 on 2023-08-09 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0005_subcategory_category_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbottomcategory',
            name='category_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kategori Numarası'),
        ),
        migrations.AlterField(
            model_name='subbottomcategory',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincategories', to='categorymodel.maincategory', verbose_name='Ana Kategori'),
        ),
    ]
