# Generated by Django 4.2.2 on 2023-06-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0006_remove_subcategory_maincategory_maincategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Kategoriler', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kategori Adı'),
        ),
    ]
