# Generated by Django 4.2.2 on 2023-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0006_subbottomcategory_category_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolFirstCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '4) Trendyol 1. Kategori',
                'verbose_name_plural': '4) Trendyol 1. Kategori',
            },
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-created_at'], 'verbose_name': '2) 2. Düzey Kategori', 'verbose_name_plural': '2) 2. Düzey Kategori'},
        ),
    ]
