# Generated by Django 4.2.2 on 2023-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0008_trendyolsecondcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolThirdCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '4) Trendyol 3. Kategori',
                'verbose_name_plural': '4) Trendyol 3. Kategori',
                'ordering': ['id'],
            },
        ),
    ]
