# Generated by Django 4.2.2 on 2023-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0008_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
    ]
