# Generated by Django 4.2.2 on 2023-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0009_trendyolthirdcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolFourCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '7) Trendyol 4. Kategori',
                'verbose_name_plural': '7) Trendyol 4. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='trendyolsecondcategory',
            options={'ordering': ['id'], 'verbose_name': '5) Trendyol 2. Kategori', 'verbose_name_plural': '5) Trendyol 2. Kategori'},
        ),
        migrations.AlterModelOptions(
            name='trendyolthirdcategory',
            options={'ordering': ['id'], 'verbose_name': '6) Trendyol 3. Kategori', 'verbose_name_plural': '6) Trendyol 3. Kategori'},
        ),
    ]
