# Generated by Django 4.2.2 on 2023-06-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0009_remove_maincategory_parent_remove_subcategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': '1) Ana Kategoriler', 'verbose_name_plural': '1) Ana Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2) Alt Kategoriler', 'verbose_name_plural': '2) Alt Kategoriler'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorymodel.maincategory', verbose_name='Ana Kategori'),
        ),
    ]
