# Generated by Django 4.2.2 on 2023-06-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0010_alter_maincategory_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['order'], 'verbose_name': '1) Ana Kategoriler', 'verbose_name_plural': '1) Ana Kategoriler'},
        ),
        migrations.AddField(
            model_name='maincategory',
            name='order',
            field=models.IntegerField(null=True, verbose_name='Sırası'),
        ),
    ]
