# Generated by Django 4.2.2 on 2023-08-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0010_trendyolfourcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolFiveCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '7) Trendyol 5. Kategori',
                'verbose_name_plural': '7) Trendyol 5. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='trendyolfirstcategory',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trendyolfourcategory',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trendyolsecondcategory',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trendyolthirdcategory',
            name='is_subcategory',
            field=models.BooleanField(default=False),
        ),
    ]
