# Generated by Django 4.2.2 on 2023-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0011_trendyolfivecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolSixCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kategori Adı')),
                ('parentId', models.BigIntegerField(blank=True, null=True)),
                ('is_subcategory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '9) Trendyol 5. Kategori',
                'verbose_name_plural': '9) Trendyol 5. Kategori',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='trendyolfivecategory',
            options={'ordering': ['id'], 'verbose_name': '8) Trendyol 5. Kategori', 'verbose_name_plural': '8) Trendyol 5. Kategori'},
        ),
    ]
