# Generated by Django 4.2.2 on 2023-08-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0012_trendyolsixcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendyolFirstCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolFiveCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolFourCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolSecondCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolSixCategory',
        ),
        migrations.DeleteModel(
            name='TrendyolThirdCategory',
        ),
    ]
