# Generated by Django 3.2.21 on 2023-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorymodel', '0013_delete_trendyolfirstcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subbottomcategory',
            options={'ordering': ('title',), 'verbose_name': '3) 3. Düzey Kategori', 'verbose_name_plural': '3) 3. Düzey Kategori'},
        ),
    ]
