# Generated by Django 4.2.2 on 2023-07-05 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0030_alter_product_variant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0009_subscription_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Sipariş Numarası')),
                ('order_total', models.FloatField(verbose_name='Sipariş Toplamı')),
                ('cardholder', models.CharField(max_length=255, null=True, verbose_name='Kart Sahibi')),
                ('cardnumber', models.CharField(max_length=20, null=True, verbose_name='Kart Numarası')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Yeni', max_length=50, null=True, verbose_name='Sipariş Durumu')),
                ('ip', models.CharField(max_length=50, verbose_name='İp Adresi')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Sipariş Verildi Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customeraddress', verbose_name='Adres')),
            ],
            options={
                'verbose_name': '2. Siparişler',
                'verbose_name_plural': '2. Siparişler',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Ödeme Numarası')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Ödeme Yöntemi')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='Ödenen Miktar')),
                ('status', models.CharField(max_length=100, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuma Tarihi')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '1. Ödemeler',
                'verbose_name_plural': '1. Ödemeler',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Renk')),
                ('size', models.CharField(max_length=50, verbose_name='Boyut')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('product_price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('ordered', models.BooleanField(default=False, verbose_name='Sipariş Verildi Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Sipariş')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Ödeme')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variants', verbose_name='Ürün Çeşidi')),
            ],
            options={
                'verbose_name': '3. Ürün Siparişleri',
                'verbose_name_plural': '3. Ürün Siparişleri',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment', verbose_name='Ödeme'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Müşterü'),
        ),
    ]
