# Generated by Django 4.2.2 on 2023-07-19 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Banka Adı')),
                ('image', models.ImageField(blank=True, upload_to='img/order/bank/', verbose_name='Banka Logusu')),
                ('ıban', models.CharField(max_length=20, null=True, verbose_name='IBAN')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': '3. Banka Bilgileri',
                'verbose_name_plural': '3. Banka Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sipariş Numarası')),
                ('order_total', models.FloatField(verbose_name='Sipariş Toplamı')),
                ('paymenttype', models.CharField(choices=[('Banka/Kredi Kartı', 'Banka/Kredi Kartı'), ('Havale/EFT', 'Havale/EFT')], max_length=30, null=True)),
                ('cardholder', models.CharField(max_length=255, null=True, verbose_name='Kart Sahibi')),
                ('cardnumber', models.CharField(max_length=20, null=True, verbose_name='Kart Numarası')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Yeni', max_length=50, null=True, verbose_name='Sipariş Durumu')),
                ('used_coupon', models.FloatField(blank=True, null=True, verbose_name='Kullanılan Kupon')),
                ('ip', models.CharField(max_length=50, verbose_name='İp Adresi')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='Sipariş Verildi Mi?')),
                ('bonuses', models.FloatField(blank=True, null=True, verbose_name='Verdiği Bonu')),
                ('approved_contract', models.BooleanField(default=False, verbose_name='Sözleşme Onayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customeraddress', verbose_name='Adres')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': '1. Siparişler',
                'verbose_name_plural': '1. Siparişler',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Renk')),
                ('size', models.CharField(max_length=50, verbose_name='Boyut')),
                ('quantity', models.IntegerField(verbose_name='Miktar')),
                ('product_price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('ordered', models.BooleanField(default=False, verbose_name='Sipariş Verildi Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variants', verbose_name='Ürün Çeşidi')),
            ],
            options={
                'verbose_name': '2. Ürün Siparişleri',
                'verbose_name_plural': '2. Ürün Siparişleri',
            },
        ),
    ]
