# Generated by Django 4.2.2 on 2023-07-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymenttype',
            field=models.CharField(choices=[('Banka/Kredi Kartı', 'Banka/Kredi Kartı'), ('Havale/EFT', 'Havale/EFT')], max_length=30, null=True),
        ),
    ]
