# Generated by Django 4.2.2 on 2023-08-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankinfo',
            old_name='ıban',
            new_name='iban',
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='account_holder',
            field=models.CharField(max_length=100, null=True, verbose_name='Hesap Sahibi'),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='account_no',
            field=models.CharField(max_length=155, null=True, verbose_name='Hesap Numarası'),
        ),
    ]
