# Generated by Django 3.2.21 on 2024-03-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20240304_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreOrder',
        ),
    ]
