# Generated by Django 4.2.2 on 2023-08-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_ıban_bankinfo_iban_bankinfo_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Ücreti'),
        ),
    ]
