# Generated by Django 4.2.2 on 2023-08-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kargo Şirketi'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_track',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Takip Kodu'),
        ),
    ]
