# Generated by Django 4.2.2 on 2023-07-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_contract',
            field=models.BooleanField(default=False, verbose_name='Sözleşme Onayı'),
        ),
    ]
