# Generated by Django 4.2.2 on 2023-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_name_order_delivery_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Takip Linki'),
        ),
    ]
