# Generated by Django 4.2.2 on 2023-07-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_approved_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '1. Siparişler', 'verbose_name_plural': '1. Siparişler'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': '2. Ürün Siparişleri', 'verbose_name_plural': '2. Ürün Siparişleri'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
