# Generated by Django 4.2.2 on 2023-08-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_track_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bonuses',
            field=models.FloatField(blank=True, null=True, verbose_name='Verdiği Bonus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cardholder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kart Sahibi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kart Numarası'),
        ),
    ]
