# Generated by Django 4.2.2 on 2023-07-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_bankinfo_alter_orderproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
