# Generated by Django 4.2.2 on 2023-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_bonuses_alter_order_cardholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='branch',
            field=models.CharField(max_length=255, null=True, verbose_name='Banka Şubesi'),
        ),
    ]
