# Generated by Django 4.2.2 on 2023-08-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_bankinfo_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_contracts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.FileField(null=True, upload_to='documents/bill/'),
        ),
    ]
