# Generated by Django 4.2.2 on 2023-07-06 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_alter_product_variant'),
        ('orders', '0007_remove_orderproduct_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.variants', verbose_name='Ürün Çeşidi'),
        ),
    ]
