# Generated by Django 4.2.2 on 2023-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_approved_contracts_order_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '1. Siparişler', 'verbose_name_plural': '1. Siparişler'},
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.FileField(null=True, upload_to='documents/bill/', verbose_name='Fatura Yükle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymenttype',
            field=models.CharField(choices=[('Banka/Kredi Kartı', 'Banka/Kredi Kartı'), ('Havale/EFT', 'Havale/EFT')], max_length=30, null=True, verbose_name='Ödeme Tipi'),
        ),
    ]
