# Generated by Django 4.2.2 on 2023-07-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonuses',
            field=models.FloatField(blank=True, null=True, verbose_name='Verdiği Bonu'),
        ),
    ]
