# Generated by Django 4.2.2 on 2023-08-13 20:35

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_options_alter_order_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_selling_contract',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi'),
        ),
        migrations.AddField(
            model_name='order',
            name='preliminary_information_form',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ön Bilgilendirme Formu'),
        ),
    ]
