# Generated by Django 4.2.2 on 2023-07-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_bonuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_coupon',
            field=models.FloatField(blank=True, null=True, verbose_name='Kullanılan Kupon'),
        ),
    ]
