# Generated by Django 4.2.2 on 2023-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='coupon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
