# Generated by Django 4.2.2 on 2023-08-31 12:59

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_preorder_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='bonuses',
            field=models.FloatField(blank=True, null=True, verbose_name='Verdiği Bonus'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='delivery_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kargo Ücreti'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='distance_selling_contract',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='preliminary_information_form',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Ön Bilgilendirme Formu'),
        ),
    ]
