# Generated by Django 4.2.2 on 2023-09-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_preorder_bonuses_preorder_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Onaylandı', 'Onaylandı'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Kargolandı', 'Kargolandı'), ('Tamamlandı', 'Tamamlandı'), ('İptal Edildi', 'İptal Edildi'), ('Ödeme Yapılmadı', 'Ödeme Yapılmadı')], default='Yeni', max_length=50, null=True, verbose_name='Sipariş Durumu'),
        ),
    ]
