# Generated by Django 4.2.2 on 2023-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='cart_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
