# Generated by Django 4.2.2 on 2023-09-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_extraditionrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraditionrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/iade/', verbose_name='İade Fotoğrafı'),
        ),
    ]
