# Generated by Django 4.2.2 on 2023-09-05 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_extraditionrequest_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraditionrequest',
            name='image',
        ),
    ]
