# Generated by Django 4.2.2 on 2023-09-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_extraditionrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraditionrequest',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Sipariş'),
        ),
    ]
