# Generated by Django 4.2.2 on 2023-09-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_extraditionrequest_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_contracts',
        ),
    ]
