# Generated by Django 4.2.2 on 2023-09-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_order_approved_contracts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraditionrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ExtraditionRequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('extraditionrequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.extraditionrequest', verbose_name='Sipariş')),
            ],
        ),
    ]
