# Generated by Django 4.2.2 on 2023-09-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_extraditionrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraditionrequestresult',
            name='typ',
            field=models.CharField(choices=[('Kabul Edili', 'Kabul Edili'), ('Red', 'Red')], max_length=255, null=True, verbose_name='İade Sonucu'),
        ),
    ]
