# Generated by Django 4.2.2 on 2023-09-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_apiproduct_options_and_more'),
        ('orders', '0026_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraditionrequestproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct', verbose_name='Ürün'),
        ),
    ]
