# Generated by Django 4.2.2 on 2023-09-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_extraditionrequestproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
