# Generated by Django 4.2.2 on 2023-09-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_cancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_cancelling',
            field=models.BooleanField(default=False, verbose_name='İptal Talebi Var Mı?'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_extradation',
            field=models.BooleanField(default=False, verbose_name='İade Talebi Var Mı?'),
        ),
    ]
