# Generated by Django 4.2.2 on 2023-09-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_remove_images_product_remove_product_brand_and_more'),
        ('orders', '0030_orderproduct_is_cancelling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraditionrequest',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.apiproduct', verbose_name='Ürün'),
        ),
        migrations.DeleteModel(
            name='ExtraditionRequestProduct',
        ),
    ]
