# Generated by Django 3.2.21 on 2023-10-01 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_extraditionrequest_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance_selling_contract',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preliminary_information_form',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ön Bilgilendirme Formu'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='distance_selling_contract',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Mesafeli Satış Sözleşmesi'),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='preliminary_information_form',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ön Bilgilendirme Formu'),
        ),
    ]
