# Generated by Django 3.2.21 on 2023-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20231001_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Taksit Sayısı'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_installment',
            field=models.BooleanField(default=False, null=True, verbose_name='Taksitli Mi?'),
        ),
    ]
