# Generated by Django 3.2.21 on 2023-10-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20231004_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_amout',
            field=models.FloatField(null=True, verbose_name='Sipariş Tutarı'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(null=True, verbose_name='Ödenen Tutar'),
        ),
    ]
