# Generated by Django 3.2.21 on 2023-10-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20231004_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_amout',
            new_name='order_amount',
        ),
    ]
