# Generated by Django 3.2.21 on 2023-10-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_rename_order_amout_order_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='forward_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Vadeli Satış Fiyatı (KDV Dahil)'),
        ),
    ]
