# Generated by Django 3.2.21 on 2023-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_orderproduct_forward_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_slug',
            field=models.CharField(max_length=500, null=True, verbose_name='Ürün Slug'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='title',
            field=models.CharField(max_length=500, null=True, verbose_name='Ürün Başlığı'),
        ),
    ]
