# Generated by Django 3.2.21 on 2023-10-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20231007_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanılan Kupon Adı'),
        ),
    ]
