# Generated by Django 3.2.21 on 2023-10-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='coupon_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanılan Kupon Adı'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='used_coupon',
            field=models.FloatField(blank=True, null=True, verbose_name='Kullanılan Kupon'),
        ),
    ]
