# Generated by Django 3.2.21 on 2023-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20231008_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BINList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Banka Kodu')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banka Adı')),
                ('bin_code', models.BigIntegerField(blank=True, null=True, verbose_name='BIN Numarası')),
                ('card_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kart Tipi')),
                ('businesscard', models.BooleanField(default=False, verbose_name='Ticari Kart')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'ordering': ['-bank_code'],
            },
        ),
    ]
