# Generated by Django 3.2.21 on 2023-10-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_preorder_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='approved_contract',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='distance_selling_contract',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='preliminary_information_form',
        ),
    ]
