# Generated by Django 3.2.21 on 2023-10-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('orders', '0044_auto_20231021_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customeraddress', verbose_name='Sipariş Adresi'),
        ),
    ]
