# Generated by Django 3.2.21 on 2023-10-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20231022_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_platform',
            field=models.CharField(blank=True, choices=[('TredyShop', 'TredyShop'), ('Trendyol', 'Trendyol'), ('Hepsiburada', 'Hepsiburada'), ('PTTAvm', 'PTTAvm'), ('N11', 'N11'), ('Çiçeksepeti', 'Çiçeksepeti')], default='TredyShop', max_length=100, null=True, verbose_name='Sipariş Verilen Platform'),
        ),
    ]
